### ISSUE TITLE
French / English / German language switch, always FR when app starts

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#100]
Is the language setting saved into persistent storage?
(tested with `npm run start:dev`)

**Comment by ikouchiha47** [comment]
Also after setting it to English, The options are shown in French.

**Comment by llemeurfr** [comment]
To commute to English (and other languages), all labels must be checked. Please complete the mapping sheet on https://docs.google.com/spreadsheets/d/1-QXpxSfnUsDVh44F0OhkAVzsEWEGatu9zZ03wNuVYRk/edit?usp=sharing

**Comment by danielweck** [comment]
This issue persists. I am reopening.

**Comment by panaC** [comment]
this is the same that #281

**Comment by danielweck** [comment]
Note that the default language should be the platform one, with a fallback to English (not French)
