### ISSUE TITLE
v1.2.1 is not properly code signed for macOS

### ISSUE THREAD

**Issue by CircularKen** [readium/readium-desktop#1016]
By default Mac will show

<img width="532" alt="Screenshot 2020-04-24 06 56 09" src="https://user-images.githubusercontent.com/17338941/80179800-2c038300-85f9-11ea-9fc9-5e25c80da77a.png">

Right Click on the app and Open to see

<img width="532" alt="Screenshot 2020-04-24 06 56 26" src="https://user-images.githubusercontent.com/17338941/80179791-2ad25600-85f9-11ea-9af1-012858f57d51.png">

**Comment by danielweck** [comment]
I cannot remember why this previous issue was closed:
https://github.com/readium/readium-desktop/issues/125

...I agree with you Ken, the initial Thorium UX on MacOS is terrible :)

**Comment by danielweck** [comment]
Let me rename this existing issue (the title is misleading / not precise enough):
https://github.com/readium/readium-desktop/issues/97

**Comment by danielweck** [comment]
Closing this duplicate. I copied Ken's original message and screenshots.
https://github.com/readium/readium-desktop/issues/97
