### ISSUE TITLE
Full screen mode could make more use of the screen

### ISSUE THREAD

**Issue by CircularKen** [readium/readium-desktop#1017]
EPUBs (especially fixed layout) when viewed in full screen mode could benefit from using more of the screen.

<img width="1280" alt="Screenshot 2020-04-24 07 03 26" src="https://user-images.githubusercontent.com/17338941/80180229-2d817b00-85fa-11ea-94b7-463b8c3feb2c.png">

Still has rather large white letterboxing top and bottom in full screen mode and so result is not a much larger page

<img width="1280" alt="Screenshot 2020-04-24 07 03 41" src="https://user-images.githubusercontent.com/17338941/80180313-69b4db80-85fa-11ea-8626-d4c23732e8ad.png">

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/commit/53bc0c8289a3a95a0d6e33da47687c1fcf014037

Thanks Ken for reporting this! :)
PS: have you noticed improvements with the GG fixed layout book? (background audio soundtrack, in-page interaction audio prompts, reader name input with sandboxed localStorage persistence). Still missing: two-page FXL spreads, and EPUB3 Media Overlays playback. We're going to be working on that soon! ;)

**Comment by danielweck** [comment]
Hi Ken, support for fixed-layout publication has improved quite a bit, and I thought you'd be interested to give the latest automated build of Thorium. Travis CI is still building ...
https://travis-ci.org/github/edrlab/thorium-reader/jobs/688906620
...but eventually the app will be available here:
https://github.com/edrlab/thorium-reader/releases

The following short video demo is silent, but there (as you well know ;) ) is a continuous background soundtrack (uninterrupted during page turns, proprietary iBooks feature), synchronized text/audio with EPUB3 Media Overlays (and iBook's proprietary in-page play/stop controls), in-page embedded iframe interactions, sandboxed localStorage reader name ("daniel"), etc.:
https://youtu.be/tHJEc_XqFAM

Let us know if you experience issues with any of your FXL titles, please.
