### ISSUE TITLE
Elements with epub:type in <aside epub:type="footnote"> are not supported

### ISSUE THREAD

**Issue by tofi86** [readium/readium-desktop#1022]
Hi,

the following HTML snippet throws an error in Thorium-1.3.0-alpha.1.2291:

<img width="1076" alt="grafik" src="https://user-images.githubusercontent.com/365118/80475880-dce78600-8949-11ea-9ec2-af2f46b92b67.png">

```html
<p id="abs_5-379" class="firstInSequence">Text vor Endnote <span id="fn_elNr-1-2-1-2-1-2-2" class="endnote"><a epub:type="noteref" role="doc-noteref" href="#fn_elNr-1-2-1-2-1-2-2_target">1</a></span> Text nach Endnote</p>
<aside class="endnote" id="fn_elNr-1-2-1-2-1-2-2_target" epub:type="footnote" role="doc-footnote" aria-label="Footnote 1">
  <div class="footnote_counter">
    <p><a href="#fn_elNr-1-2-1-2-1-2-2" epub:type="referrer" role="doc-backlink">1</a></p>
  </div>
  <div class="footnote_content">
    <p id="fn-abs_7-381">Text in Footnote</p>
  </div>
</aside>
```

Adding the `xmlns:epub` namespace on the `a` element does not help.

If I remove the `epub:type="referrer"` it works:

<img width="1076" alt="grafik" src="https://user-images.githubusercontent.com/365118/80476019-14eec900-894a-11ea-9cc5-384100075410.png">

It seems that every `epub:type`attribute is not supported in the footnote/endnote popup. Any chance to get this fixed?

/cc @duenckel

**Comment by danielweck** [comment]
Hello, I copy-pasted your HTML snippet into a test EPUB, and I am seeing this error in the console:
```
Error: Failed to execute 'insertAdjacentHTML' on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.

Error: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
```

...I'm investigating.

**Comment by danielweck** [comment]
Fixed in the navigator component. I will update Thorium later tomorrow. Thank you very much for bringing up the issue!

**Comment by tofi86** [comment]
Awesome, thanks a lot for the quick fix! Looking forward to the next pre-release!

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/commit/5f6d68eb315feadf8a9cf48e3960a97a4b40f988

Windows CI: https://ci.appveyor.com/project/danielweck/readium-desktop/builds/32547783
Linux, MacOS CI: https://travis-ci.org/github/readium/readium-desktop/builds/681339774

CI builds should be available within the next 30 minutes here:
https://github.com/readium/readium-desktop/releases

**Comment by tofi86** [comment]
I tried with `Thorium-1.3.1-alpha.1.2312.dmg` and it works! Thanks!

**Comment by danielweck** [comment]
Thanks for letting us know.
Note that `r2-testapp-js` is a maintained lightweight Electron app (reader window, no library / bookshelf view) used to test-drive the internal Readium2 components, so it includes this bugfix.
https://github.com/readium/r2-testapp-js/releases

**Comment by danielweck** [comment]
Follow-up fix: https://github.com/edrlab/thorium-reader/commit/3b0ad13e77326ff3cd4fefcddcbcf3c4bb5ed620
