### ISSUE TITLE
incorrect saga/action for win activate?

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#1038]
Mismatch: `appActivate` vs. `winActions.library.closed.ID`

https://github.com/readium/readium-desktop/blob/321c18b97bdee43f3619de085d2a733f5ad6ccc2/src/main/redux/sagas/win/library.ts#L240-L244

**Comment by danielweck** [comment]
Clarification: if I am not mistaken, when the user closes the library window, the app closes all reader windows, and finally the application gracefully shuts down (i.e. services teardown, before exiting the process).
So, why listen to the "activate" event when the library "close" action is triggered?

**Comment by panaC** [comment]
i agree i was wrong
I will fix it

**Comment by danielweck** [comment]
By the way, I like how you are incorporating the `app.on()` Electron events into Redux Saga channels, so that the lifecycle is entirely expressed as a flow of Sagas. Nice :)

**Comment by panaC** [comment]
thanks
