### ISSUE TITLE
Library view, Grid vs. List button icon labels are "Add EPUB"

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#104]
(see SVG title in markup)

Note that although there is currently no visual manifestation of the textual label associated with the button icons (e.g. temporary popup tooltip, or permanent underline), screen readers do pick-up the title of the SVG markup that renders the button.

Related issues: https://github.com/edrlab/readium-desktop/issues/102 and https://github.com/edrlab/readium-desktop/issues/103

**Comment by llemeurfr** [comment]
It almost a details but for blind people it is misleading: now the Grid and List icons are structured as a/svg and the label is supported by a/@title, which is in English:
for the grid view "Books cover in grid view" 
for the list view "Books cover in list view". 

This is bad English + too long for being easy to understand + false, please update these labels to:
for the grid view "Grid view" 
for the list view " List view".

**Comment by llemeurfr** [comment]
fixed directly via d1e47fe14ff3f342375be425b2786bc20732179f
