### ISSUE TITLE
SMIL Media Overlay isn't working

### ISSUE THREAD

**Issue by vkiranmaniya** [readium/readium-desktop#1051]
TTS works fine but the media overlay isn't working in audiobooks. also the `.ABook` extension files are not supported. Is there any workaround?

**Comment by panaC** [comment]
Hello,

What is the reason to feeding Thorium with the `.ABook` extension ?

**Comment by danielweck** [comment]
what is an ABook? (link to specification, please)

**Comment by danielweck** [comment]
Support for SMIL EPUB Media Overlays is coming :) ...

https://github.com/readium/readium-desktop/issues/939
