### ISSUE TITLE
Question: LSD / LCP check network timeout: is the user allowed to read the book?

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#110]
Hello Cyrille, just checking with you (I have not tested this myself yet, and I do not know where to look in the codebase): what happens in case of network timeout / "airplane mode" (wifi off)? As per the LCP specs. the user should be able to read the book even if on the server-side, the LCP license is expired/returned, and even if the initial `register` LSD interaction fails.

**Comment by clebeaupin** [comment]
Currently it will work because I have not forced the renew of lcp license each time I click on view button

**Comment by danielweck** [comment]
Closing this answered question.
