### ISSUE TITLE
0.0.1-alpha1 gives unidentified developer warning on Mac OS

### ISSUE THREAD

**Issue by CircularKen** [readium/readium-desktop#125]
The Mac app 0.0.1-alpha1 is not signed with a developer certificate and so cannot be opened by double clicking. (BTW the workaround on Mac is to ctrl click and then choose 'open' and concisely decide to open an unsigned app.)

<img width="532" alt="screenshot 2018-03-27 10 21 57" src="https://user-images.githubusercontent.com/17338941/37960180-d966827a-31ac-11e8-8f21-337c1e809065.png">

**Comment by danielweck** [comment]
possible solution:
https://www.electron.build/code-signing

**Comment by danielweck** [comment]
also see:
https://help.apple.com/xcode/mac/current/#/dev033e997ca

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/97
