### ISSUE TITLE
missing label translations: "Cancel" "Oui" and "Non"

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#128]
This commit https://github.com/edrlab/readium-desktop/pull/126/commits/fba51fcded157086b59d31d892737e76a0ad5cac for the in-progress Pull Request #126 adds a number of missing SVG `<title>` translations (see related issues #102 #103 #104).

Now, I have also noticed hard-coded `label="Oui|Non|Cancel` in `App.tsx` ( https://github.com/edrlab/readium-desktop/blob/develop/src/renderer/components/App.tsx ) and `AppToolbar.tsx` ( https://github.com/edrlab/readium-desktop/blob/develop/src/renderer/components/AppToolbar.tsx ).

**Comment by tofi86** [comment]
This is the following issue, right?

![bildschirmfoto 2018-04-02 um 13 25 45](https://user-images.githubusercontent.com/365118/38195581-6457f488-367e-11e8-9dd0-a5510ed45de9.png)
![bildschirmfoto 2018-04-02 um 13 31 44](https://user-images.githubusercontent.com/365118/38195582-64734b0c-367e-11e8-8917-ba5048d0e21b.png)

**Comment by tofi86** [comment]
Alright, will looking forward to see the changes implemented...

**Comment by MyDK** [comment]
Hi Daniel 
I just tested ReadiumDesktop.Setup.1.0.0-alpha.2 
The language issue is still present in both English and German "Import" and "Delete" windows.
![import-wrong-language-on-bottons](https://user-images.githubusercontent.com/30153047/41736254-3acdea30-758c-11e8-8f9d-998e9fd1f644.JPG)
