### ISSUE TITLE
[UI/UX] Handling tables

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-desktop#140]
Tables have always been quite an issue and their rendering can become quite terrible in CSS multicol (cells being cut off, vertical padding not being properly handled, etc.). 

There’s no easy way out there, and it’s probably up to authors to find solutions but we can at least try reaching interop with some popular apps that will open the table in a dedicated web view/modal (on top of the current one, with a close button) if the user double-clicks or double-taps one. 

A few notes as to why this should be reasonable: 

- authors’ scripting is already taking this feature into account since you can find it in iBooks for instance; 
- for large tables, that would allow `overflow-x` (on the web view itself), something we can’t easily do in the paged and scrolled views (we would have to add an extra wrapper around the `table` since `overflow` won’t work for `table` itself…);
- it is expected styling for the `table` (excepted inline `style=""`) will not apply in the dedicated web view; 
- there will be huge tables to handle as people can become very creative when it comes to finding reasons why those tables must absolutely stay as they are in print (personally encountered the “moral rights of the author” justification a few years ago). 

Please feel free to add your thoughts, obviously.

**Comment by panaC** [comment]
@danielweck does it concern you?

**Comment by danielweck** [comment]
Let's close this. This is really a ReadiumCSS and navigator concern.

**Comment by llemeurfr** [comment]
@JayPanoz has proposed elsewhere to have a discussion on EPUB & tables in the W3C EPUB Community Group and I agree this is where discussions about interop should first be held. 
Then we'll open an issue in the Navigator repo (for each platform).

**Comment by JayPanoz** [comment]
Just in case, I’ll reiterate there’s literally nothing ReadiumCSS can do well enough in and of itself here, not even `overflow: scroll` because I’d have to [throw table semantics out with the bathwater](https://developer.paciellogroup.com/blog/2018/03/short-note-on-what-css-display-properties-do-to-table-semantics/) by make `table` a block element. In other words, we would need an extra element (like `div`) wrapping `table` to even apply `overflow` – so altering the DOM, which brings other complications. 

Actually, the more I’ve been thinking about this, the more I see JS as the only viable option – I know that if I had to re-tackle tables today in the authoring context, I’d probably go with a custom element because it would be easier to handle than an additional JS plugin modifying `<table>` on the fly. But boy that’s a lot of work – hence my 2 tweets btw.
