### ISSUE TITLE
GitHub Project vs. Waffle vs. ZenHub

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#141]
There seems to be a general consensus in the Readium2 team (notably: @HadrienGardeur and @aferditamuriqi ) that ZenHub is better than Waffle for cross-repository issue management ("Epics"), milestones/releases, activity reports, etc.

Suggestion: discuss benefits of ZenHub vs. GitHub Projects (the latter is currently used for readium-desktop, but other projects have been using ZenHub for some time now).

Note that Readium1 started the trend of using Waffle ( https://waffle.io/readium/readium-js-viewer ), but this is not actively used right now, and ZenHub offers more features even in its free version.

For references:

GitHub Projects:
https://github.com/edrlab/readium-desktop/projects

Waffle:
https://waffle.io/edrlab/readium-desktop

ZenHub:
https://app.zenhub.com/workspace/o/edrlab/readium-desktop/boards?repos=85566485

**Comment by danielweck** [comment]
Mailing list discussion:
https://groups.google.com/forum/#!topic/readium-dev/Q3B-6ldeYxA

**Comment by llemeurfr** [comment]
An advantage of ZenHub over Waffle is its integration in the Github repo page, using Github authentication.
When compared to Github Projects, it is cross-repo, which is a requirement for our projects.  
Cross-repo is also an advantage of ZenHub Releases over Github Milestones.

The only caveat with ZenHub is IMO that it is slow.

**Comment by danielweck** [comment]
Also note that ZenHub's feature-set is richer because they store addionnal layers of information (e.g. the notion of "epics") on top of GitHub's own labels, milestones, etc., whereas Waffle relies on a special vocabulary to implement additional semantics (e.g. child/parent relationship expressed via labels)

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/readium-desktop/issues/147

**Comment by raja** [comment]
Just curious where Readium ended up on the zh/gh projects debate?

**Comment by danielweck** [comment]
Here in `readium-desktop` the GitHub "projects" feature is used:
https://github.com/readium/readium-desktop/projects
...but if I understand correctly there is also an issue / release tracker which is internal to the core developers' management system, so sometimes there is lag in reflecting the progress status here in the `readium-desktop` GitHub issue tracker.

For the underlying `r2-xxx-js` projects (e.g. `r2-navigator-js`, `r2-streamer-js`, `r2-shared-js`, etc., but also the "test app" `r2-testapp-js`): GitHub's "projects" feature is not used to manage releases, only the issue tracker and pull requests.

I think ZenHub is actively used (on top of GitHub) in the iOS-Swift and Android-Kotlin Readium2 projects (to be verified).

**Comment by aferditamuriqi** [comment]
Yes I can confirm ZenHub is used for all Swift and Kotlin projects

**Comment by panaC** [comment]
let's go to use zenHub :+1:

**Comment by llemeurfr** [comment]
During the last Readium Meetup last week in Paris, we decided to setup ZenHub for Readium Desktop.
