### ISSUE TITLE
Suggestion: increment version number in package.json as soon as master is release-tagged, and back-merged to develop

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#145]
# Problem

Right now the `package.json` version field is `1.0.0-alpha.1` in the `master` branch:
https://github.com/edrlab/readium-desktop/blob/2384c542b5a0bfb379a4274a694f18cf99fcdfd3/package.json#L3
( https://github.com/edrlab/readium-desktop/blob/master/package.json#L3 )

...which is correct, as per the release tag:
https://github.com/edrlab/readium-desktop/blob/v1.0.0-alpha.1/package.json#L3

However, there was no version bump in the `develop` branch (immediately after back-merging the `master` branch into `develop`).
https://github.com/edrlab/readium-desktop/blob/011a75e8663c6d58df6a5f4d298bce2eb99603c9/package.json#L3
( https://github.com/edrlab/readium-desktop/blob/develop/package.json#L3 )

As a result, all the ongoing development is identifiable as `1.0.0-alpha.1` during continuous integration, etc. This also does not match the GitHub Project label `V1.0.0-alpha.2` ( https://github.com/edrlab/readium-desktop/projects/2 ) 

# Solution (?)

So, I would like to suggest an improvement to our release process (please share your thoughts):

1) `develop` is ready to release (e.g. version `1.0.0-alpha.1`): merge to `master` (implicit "no fast forward" => a merge commit is created at the head of the branch), and create a release tag on this merge commit.
2) "back"-merge `master` to `develop` with fast-forward (no creation of merge commit).
3) bump version to "next" (e.g. `1.0.0-alpha.2`)
4) carry on developing until ready (via feature branches / pull requests), manage hot fixes (to both `master` and `develop` then goto (1)

We currently use a lightweight GitFlow methodology (e.g. no `release` branches), but we can easily manage hot fixes to `master` *and* `develop` if we take care of versioning adequately. See:
https://datasift.github.io/gitflow/IntroducingGitFlow.html
https://danielkummer.github.io/git-flow-cheatsheet/
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
http://nvie.com/posts/a-successful-git-branching-model/
etc. :)

**Comment by llemeurfr** [comment]
From now, we'll be able to start merging the new code in the master branch. Before we do this, I'd like to review with the devs what we can do in a week or so which would make a release "clean" enough to merit its place on master, with a tag (I suggest 1.0.0.beta.3, as the 2 releases made on the Windows Store can be considered beta.1 and beta.2). 
Let's have this discussion before and during the next Readium call. 

Regarding Daniel's proposal for the proper management of version increments, I 100% agree with it (including not trying to adopt a full Gitflow strategy at this time).

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/98

**Comment by danielweck** [comment]
This issue can be closed now, because usage of PR squash-merging, not GitFlow methodology, etc.
The principle of bumping-up semantic versioning in the development "trunk" after release-tagging `develop` (and also subsequently merging into `master`) still applies, as described here:
https://github.com/readium/readium-desktop/issues/664
