### ISSUE TITLE
A method to File > Open and to handle 'Open with'

### ISSUE THREAD

**Issue by CircularKen** [readium/readium-desktop#150]
As is common for desktop applications it will be expected for Readium Desktop to have a File > Open command and also to be able to open EPUBs from the OS. And to inform the OS that Readium Desktop can open EPUBs (currently it is not a recommended application).

![screenshot 2018-05-10 16 47 28](https://user-images.githubusercontent.com/17338941/39879175-08bfaf32-5472-11e8-812a-6602910918ee.png)

Also related, ideally the Readium Desktop app would be able to handle EPUBs handed off from InDesign.

<img width="763" alt="screenshot 2018-05-10 16 50 13" src="https://user-images.githubusercontent.com/17338941/39879253-3c18c4cc-5472-11e8-92d6-2d9579008382.png">

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/readium-desktop/issues/85

**Comment by llemeurfr** [comment]
done
