### ISSUE TITLE
UI accessibility: list of books

### ISSUE THREAD

**Issue by gregoriopellegrino** [readium/readium-desktop#154]
OS: Windows 10
Assistive technology: NVDA 2018.1.1

- It's not simple to read the list of all the books (using AT), is it a list?
- AT finds buttons "Read" and "Delete" but doesn't know which is the target book

**Comment by panaC** [comment]
I believe this has been solved

**Comment by danielweck** [comment]
Let's close this old UI which relates to the old UI. That being said, we need to do a complete review of screen reader voice feedback on the library controls.
