### ISSUE TITLE
UI accessibility: font-size input

### ISSUE THREAD

**Issue by gregoriopellegrino** [readium/readium-desktop#158]
OS: Windows 10
Assistive technology: NVDA 2018.1.1

When changing font-size in the UI there is no feedback to assistive technology, so user doesn't know the value selected.

**Comment by MyDK** [comment]
When changing font-size in "Settings" window, and choosing NOT to save changes - my changes are (rightfully) NOT applied. Great.
But when I open "Settings" again, my choises are still there (and not applied). It is not a big deal, but it gives the wrong impresson, so maybe it is considered a bug? 
![settings-change-dont-keep-changes](https://user-images.githubusercontent.com/30153047/41736644-690cb970-758d-11e8-9a12-ee1c170a7ba9.JPG)

**Comment by panaC** [comment]
we can close it

**Comment by danielweck** [comment]
Let's close this old UI which relates to the old UI. That being said, we need to do a complete review of screen reader voice feedback on slider controls, etc.
