### ISSUE TITLE
32bit build for Windows

### ISSUE THREAD

**Issue by naorunaoru** [readium/readium-desktop#165]
Hi. 

So I don't really know how build system works here, but maybe someone can answer my question: is there anything that prevents making a 32bit build for Windows?

**Comment by JayPanoz** [comment]
You can add 

```
"package:win32": "npm run package:build && build --win --ia32"
```

in package.json here: 

https://github.com/readium/readium-desktop/blob/26f2fdae1becdc70638a39dd4e96f76dff0786df/package.json#L34-L38

It’s been reported to work by someone else on the Readium Desktop Slack Channel. I quote

> i added this to the package.json and created a package on a win32 machine. It is 10mb smaller than the 64bit version.

**Comment by naorunaoru** [comment]
@JayPanoz Thanks a lot, I'll try it on my crap-tier x86 tablet and see if there are any issues.

**Comment by llemeurfr** [comment]
Pls re-open if this solution does not work.
