### ISSUE TITLE
Would be nice to have an msi installer on Windows

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-desktop#166]
I’ve just came across this issue @ enssib: we need apps for eprdctn. However, `.exe` becomes an issue for deployment and there is no guarantee IT will get around it. 

That could impact others as well, judging by the following issue in Visual Studio Code for instance: https://github.com/Microsoft/vscode/issues/33184

**Comment by JayPanoz** [comment]
Actually, Electron-wix-msi readme explains the differences, use-cases, etc. if needed: https://github.com/felixrieseberg/electron-wix-msi/#readme

**Comment by llemeurfr** [comment]
The app will be on the Windows Store in the coming days.
