### ISSUE TITLE
[bug]xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by librix** [readium/readium-desktop#167]
if document has a string "&&" or "&" ，it will eject an error ："xmlParseEntityRef: no name";

to solve this problem is to change the "&" to "&amp;" in epub book itself, but its not a good choose.so I think this is a bug.

`$text=preg_replace('/&(?!#?[a-z0-9]+;)/', '&amp;', $text);`

The bug could be react with this file [testBook.zip](https://github.com/readium/readium-desktop/files/2501106/testBook.zip)

**Comment by danielweck** [comment]
Thank you for reporting.
* First of all, the filename is `JavaScript∏ﬂº∂≥Ã–Ú…Ëº∆£®µ⁄3∞Ê£©.epub`. This does not seem to cause issues though :)
* When checking this problem with `r2-testapp-js` (which utilises the same low-level components as `readium-desktop`, behind the scenes), I see this message in the console:
```
[xmldom warning]	unclosed xml attribute 
@#[line:75,col:17]
[xmldom warning]	unclosed xml attribute 
@#[line:93,col:17]
```
Let me look into this....

**Comment by danielweck** [comment]
Ah, your XHTML document is not valid. You must escape occurrences of the ampersand character `&` with `&amp;` (even inside `<pre> ... </pre>` fragments), otherwise a markup parser will attempt to interpret `&` as the beginning of an "entity" (which ends with a semicolon, e.g. `&xxx;`).
