### ISSUE TITLE
Rename application to edrlab-desktop

### ISSUE THREAD

**Issue by clebeaupin** [readium/readium-desktop#174]
In package.json rename app readium-desktop to edrlab-desktop

**Comment by danielweck** [comment]
Also in `nodeExternals.js`:
https://github.com/readium/readium-desktop/blob/26f2fdae1becdc70638a39dd4e96f76dff0786df/nodeExternals.js#L114
( https://github.com/readium/readium-desktop/blob/master/nodeExternals.js#L114 )

**Comment by danielweck** [comment]
Also TypeScript config path/alias (and all the TS code imports):
https://github.com/readium/readium-desktop/blob/26f2fdae1becdc70638a39dd4e96f76dff0786df/tsconfig.json#L14
( https://github.com/readium/readium-desktop/blob/master/tsconfig.json#L14 )

**Comment by danielweck** [comment]
Also in all the `webpack.config.*` files where the aforementioned `readium-desktop` path/alias are used.

**Comment by clebeaupin** [comment]
Rename alias from "readium-desktop" to "app"

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/211
