### ISSUE TITLE
OPDS (v1) feed is XML, but not necessarily with XML "header"

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#193]
https://github.com/readium/readium-desktop/blob/e04a6a06522e37250c1505c45c0952d57a4f9e86/src/main/api/opds.ts#L75

This XML "header" check will exclude *many* OPDS feeds, so I suggest removing it.

For testing, here is a repository of open-access feeds:
https://github.com/readium/r2-streamer-js/blob/develop/docs/opds.md
(note that not all OPDS publication "acquisitions" are public-domain, but at least the feeds themselves can be tested)

**Comment by llemeurfr** [comment]
It's true that the XML declaration (<?xml version="1.0" encoding="utf-8" ?>) is optional (even if recommmended). By default the encoding is "utf-8"; an xml parser knows that. 

Isn't the feed mimetype (json vs xml) usable here?

**Comment by llemeurfr** [comment]
done
