### ISSUE TITLE
EPUB "regime anticancer arabic" fails to import, crashes the bookshelf library (lang map metadata)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#205]
Book source:

https://github.com/IDPF/epub3-samples/tree/master/30/regime-anticancer-arabic
( https://github.com/IDPF/epub3-samples/releases/download/20170606/regime-anticancer-arabic.epub )

See the usage of "language map" objects (in particular, `author` and `title`):

https://readium2.herokuapp.com/pub/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0lEUEYvZXB1YjMtc2FtcGxlcy9tYXN0ZXIvMzAvcmVnaW1lLWFudGljYW5jZXItYXJhYmljL01FVEEtSU5GL2NvbnRhaW5lci54bWw%3D/manifest.json/show/all

Alternative link (in case the above fails):

https://readium2.now.sh/pub/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0lEUEYvZXB1YjMtc2FtcGxlcy9tYXN0ZXIvMzAvcmVnaW1lLWFudGljYW5jZXItYXJhYmljL01FVEEtSU5GL2NvbnRhaW5lci54bWw%3D/manifest.json/show/all

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/206

**Comment by danielweck** [comment]
I have fixed this issue using a two-prong approach:

https://github.com/readium/readium-desktop/commit/3e0ce622172886e7066d56777d98ab7c7cb58bb7

(note that this commit is part of this PR https://github.com/readium/readium-desktop/pull/202 )

1) in `src/main/services/catalog.ts` so that newly-imported EPUBs set the correct title (that is the main bugfix)
2) in `src/main/db/repository/publication.ts` so that already-imported EPUBs with multilang `title` ("corrupted" database) do not crash the app at startup (that fix should be reviewed, because this is really just a workaround)

**Comment by llemeurfr** [comment]
Another IPDF sample, kusamakura-japanese-vertical-writing.epub, also crashes the app when imported. 
I hope this will be solved after the PR is applied.

**Comment by llemeurfr** [comment]
Issue solved for the arabic ebook.
