### ISSUE TITLE
Drag-drop of HTTP URL on reader view's chrome / UI => BrowserWindow loads URL!

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#210]
This default Electron behaviour can be stopped using the following code snippet:

```javascript
    window.document.addEventListener("dragover", (ev) => {
        ev.preventDefault();
        return false;
    }, false);

    window.document.addEventListener("drop", (ev) => {
        ev.preventDefault();
        return false;
    }, false);
```

Note that the main "navigator" rectangular area in the reader view already intercepts links / navigation events (it automatically opens an external web browser for HTTP URLs not recognized by the navigator instance).

The BrowserWindow for the library view already handles drag/drop for local files, not so affected by this bug.

**Comment by panaC** [comment]
It seems to be fixed

**Comment by danielweck** [comment]
Yes indeed, this seems to be fixed now. Not sure what changed in the code.

The reader view does not have a `DropZone`, so I am not sure what currently prevent the `drop` events:
https://github.com/readium/readium-desktop/blob/541e48bbe45407a8918018e0076d4ca5ebecd68b/src/renderer/components/reader/App.tsx#L28-L33

Conversely, the library view has a `DropZone` which handles local files:
https://github.com/readium/readium-desktop/blob/541e48bbe45407a8918018e0076d4ca5ebecd68b/src/renderer/components/App.tsx#L78-L108

Oh well, the bug does not exist anymore, so let's close :)

**Comment by danielweck** [comment]
PS: maybe the change from Electron v1 to v3 introduced this new behaviour.
