### ISSUE TITLE
Allow download of publications in OPDS feeds

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#219]
Download is allowed if the link type is 
http://opds-spec.org/acquisition or http://opds-spec.org/acquisition/open-access
-> "Add to the library"
http://opds-spec.org/acquisition/sample or http://opds-spec.org/acquisition/preview
-> "Add the sample to the library"

**Comment by danielweck** [comment]
Are LCP license links supported?

```xml
<link
rel="http://opds-spec.org/acquisition"
href="https://example.com/book.lcpl"
type="application/vnd.readium.lcp.license-v1.0+json"
/>
```

CC @kevinmainairungu

**Comment by mutterback** [comment]
Thank you Daniel. Let's discuss on the Readium  call. Here's a screen of the error we get when attempting to do this.
![add opds to library](https://user-images.githubusercontent.com/18404465/55887580-bd818d80-5b7b-11e9-84d1-872784b8ddb8.jpg)

**Comment by HadrienGardeur** [comment]
> http://opds-spec.org/acquisition/sample or http://opds-spec.org/acquisition/preview

This should be `http://opds-spec.org/acquisition/sample` or `preview`.

Downloading an LCP License should IMO be supported at least for `http://opds-spec.org/acquisition` and `http://opds-spec.org/acquisition/open-access`.

In addition, I would recommend supporting the following `rel` values when they point to an HTML resource:

- `http://opds-spec.org/acquisition/buy`
- `http://opds-spec.org/acquisition/borrow`
- `http://opds-spec.org/acquisition/subscribe`

Readium Desktop should also consider support for [Authentication for OPDS](https://drafts.opds.io/authentication-for-opds-1.0) in the future.

**Comment by dobbz** [comment]
I may be wrong but it seems it is partially supported. Adding an LCP opds feed works and one can browse the titles in the feed. However, when adding any book to the library then we get the error shown in the picture without the book ever downloading. 

We would like to further investigate this further and any pointers on where to start would be appreciated 

CC @kevinmainairungu

**Comment by llemeurfr** [comment]
Download of unencrypted & free EPUB files (for open-access, sample and preview rels) is now allowed. A proper notification of download ok/ko is missing, it will be added very soon. 

Support of buy/borrow/subscribe relations will be developed in a subsequent version -> see #245  
Support of an LCP acquisition feed is not developed yet, it will be added very soon -> let's leave this issue open until solved.

**Comment by llemeurfr** [comment]
Warning: the LCP MIME media type is `application/vnd.readium.lcp.license.v1.0+json`
and *not* (as written above) application/vnd.readium.lcp.license-v1.0+json

**Comment by llemeurfr** [comment]
@HadrienGardeur 

> This should be http://opds-spec.org/acquisition/sample or preview.

do you mean we should process rel="preview"?

**Comment by llemeurfr** [comment]
Downloading samples is now possible, from OPDS feeds.
