### ISSUE TITLE
Change in design: home screen, Explore All move to the sub-navigation bar

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#224]
The Explore All (Tous les livres) button is currently on the right of the "Recently Added" selection, which will make no sense when we add the "Resume Reading" selection. 

Let's move it to the My Books sub-navigation bar, below Preferences, black color (= active), font size equal to the font of the Search label and aligned vertically with the Search label.

**Comment by llemeurfr** [comment]
done

**Comment by manuellagrand** [comment]
solved via PR #226
