### ISSUE TITLE
LCP LSD device name is currently `readium-desktop`, will need to be updated to Thorium's own human-readable identifier

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#230]
The LSD status document "events" section lists these human-readable names, so it is important that this gets updated when migrating from `readium-desktop` to "Thorium".

https://github.com/readium/readium-desktop/blob/663099c027717d3e58cdb772f1d2d1d2c68c2989/src/main/di.ts#L203

Note that `r2-testapp-js` utilises `Readium2 Electron desktop app`.

**Comment by Scarsniik** [comment]
fixed in 7f12fb2281f4051af3a490d97975b0f19f1fd218
