### ISSUE TITLE
Align book cover on the bottom

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#238]
Result of a discussion with a designer. The covers are currently fit to width and centered aligned vertically. But (free) ebooks can have very different cover geometries and the result can be bad. 

Existing services use very different solutions:  
Kobo (bottom aligned): https://www.kobo.com/fr/fr/ebooks/trendingnow
Google Play (covers in grey blocks, with barscopes): https://play.google.com/store/books
Decitre (vertical fit):  https://www.decitre.fr/ebook/jeunesse/romans-ados.html
ePagine  (vertical fit, small cover) : https://www.epagine.fr/listeliv.php?refgtl=home&base=ebook&select_tri_recherche=&rayon=Litt%C3%A9rature+g%C3%A9n%C3%A9rale&codegtl1=1000000

We'll try a fit to with + bottom alignment.

**Comment by manuellagrand** [comment]
solved via PR #248
