### ISSUE TITLE
Closing  the app should close detached windows

### ISSUE THREAD

**Issue by manuellagrand** [readium/readium-desktop#257]
when the home window is detached of the reader window and we close the home window, it should close all windows open

**Comment by llemeurfr** [comment]
Steps: 
- Open a book
- Detach the reading window
- close the main window
The app is not closed and the reading window is still open. To quit the app, the user must go to the top system menu. 

Normal behavior: 
When the main window is closed, all detached windows should be also closed and the app should also be.
