### ISSUE TITLE
Rename app name to Thorium

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#258]
Replace readium-desktop -> Thorium in 

https://github.com/readium/readium-desktop/blob/af99057508f14f48aeef144ef60c124f1bb23348/package.json#L2-L3
https://github.com/readium/readium-desktop/blob/af99057508f14f48aeef144ef60c124f1bb23348/package.json#L63-L64

https://github.com/readium/readium-desktop/blob/develop/src/resources/docs/en/about.md
https://github.com/readium/readium-desktop/blob/develop/src/resources/docs/fr/about.md

**Comment by manuellagrand** [comment]
solved by #264
