### ISSUE TITLE
Microsoft Store, signed AppX via electron-builder

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#261]
Currently NSIS:

https://github.com/readium/readium-desktop/blob/af99057508f14f48aeef144ef60c124f1bb23348/package.json#L105-L107

Electron Builder documentation:
https://www.electron.build/configuration/appx

https://electronjs.org/docs/tutorial/windows-store-guide

**Comment by danielweck** [comment]
Hello @Scarsniik , I see this commit ( https://github.com/readium/readium-desktop/commit/68e4dc0da4bdcd5753a413d8a1c26f29ff336702#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 ) introduces the `nsis-web` target for `electron-builder`:
https://github.com/readium/readium-desktop/blob/a3857ea58cc9b01d3d26a137a2f2e56690b49495/package.json#L104-L105

I am assuming this change was made in preparation for the Windows Store deployment?
If so, have you considered a signed AppX, as per https://www.electron.build/configuration/appx ?

**Comment by Scarsniik** [comment]
Hello,
Yes, it's for the Windows Store.
I used this doc and I think it works. I didn't see anything strange

**Comment by danielweck** [comment]
The Microsoft consultant who is advising / helping us asked about the signed AppX bundle. I assumed that the Electron Builder built-in support for AppX would be most appropriate (judging by the documentation). What about nsis-web, does that generate a signed bundle compatible with AppX / Windows Store deployment?

**Comment by Scarsniik** [comment]
Yes, it create a .appx

**Comment by danielweck** [comment]
Great. I would like to better understand the difference between nsis-web and appx electron-builder targets, just to make sure choosing nsis-web now does not impede future migration to appx target.
I will read the electron-builder doc again. Let me know if you have insights on this already.

**Comment by danielweck** [comment]
more info https://www.electron.build/configuration/win

**Comment by kevinmainairungu** [comment]
Hi @danielweck  - these are the steps we took to package the appx.
[electron](https://www.electron.build/configuration/win)
 [configuration to windows store and signng](https://electronjs.org/docs/tutorial/windows-store-guide)
Here is the list of Blocked executable from the Microsoft certification tool 

[logs.txt](https://github.com/readium/readium-desktop/files/3232625/logs.txt)


and the log events from the code integrity checker




[events.txt](https://github.com/readium/readium-desktop/files/3232622/events.txt)

Also here are the requirements for pushing an app to the store with 10s requirements

However, we're still getting security violations for Windows 10S
They allowed us to post on the Store, but the app cannot be added to devices running in Windows 10S mode, which MSFT recommends for all educational deployments
Therefore, you'll need to add a note stating that the app does not work on 10S
Here is the log file listing the violations for 10S, attached.
We are very interested in collaborating to solve these issues
please let us know how we can help

**Comment by kevinmainairungu** [comment]
@danielweck  windows 10s requirements

**Comment by danielweck** [comment]
Thank you Kevin!
You used the `electron-windows-store` utility to generate the AppX from the output of `electron-packager`, therefore you did not use the `appx` target of electron-builder target to sign the app bundle, right?
https://www.electron.build/configuration/appx

**Comment by kevinmainairungu** [comment]
no i did not use the  appx target of electron-builder.

**Comment by llemeurfr** [comment]
The APPX has now been submitted to the Microsoft Store; submission 1. Waiting for approval.
