### ISSUE TITLE
On first use, show a simplified screen

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#278]
When the app is used for the first time, the database is empty. The user currently sees empty Resume Reading and Recently Added sections. Plus a My Tags section with a label "there is no tags in books.". 

In this case, display a large dotted rectangle  containing a + icon with a label "To import ebooks, drag&drop EPUB files here or use the plus button in the menu above.".

**Comment by llemeurfr** [comment]
After he has imported books, and until he opens a first book, the  Resume Reading is empty. We have to hide it from the view of the user.

**Comment by Scarsniik** [comment]
fixed in 16ce135
