### ISSUE TITLE
Reading view, issue with the highlight of panel icons 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#283]
Context: a book is open. 
Click on the "Aa" icon: it should be highlighted. It is not.
Click on the "open book" button: it should be now highlighted. It is not, but the "Aa" button is. 

Expected:
Click on the "Aa" icon: it is highlighted. The "open book" is not.
Click on the "open book"  icon: it is highlighted. The "Aa" is not.

**Comment by manuellagrand** [comment]
related to: #288
