### ISSUE TITLE
Book information, crop the text if too long 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#285]
Context: from the Feedbooks OPDS feed, load "The Great Gatsby" ("Free books", "Most popular"). Open the book information modal window.

The description of this book is very long and a disgraceful scrollbar appear immediately, whatever the size of the window. 
A solution is to display 1000 characters max, and add a "Read more" button. If clicked, the remaining text will appear. 
Re. accessibility: this button is not shown to the user, as the whole text can be accessed by the screen reader.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/370

**Comment by Scarsniik** [comment]
fixed in bd0a28e
