### ISSUE TITLE
Improper label translations

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#286]
In the book information windows:

In english, "language" -> "Language"; "identifier" -> "Identifier". 
In french, "langue" -> "Langue"; "identifiant" -> "Identifiant".

**Comment by llemeurfr** [comment]
In the text display related settings:

In english: "Predifined themes" -> "Predefined themes"
"Without" -> "Neutral"
"Justify" -> "Justified"
"2 column" -> "2 columns"
"Words spacing" -> "Word spacing"
"Letters spacing" -> "Letter spacing"

**Comment by llemeurfr** [comment]
In the actions related to OPDS feeds:

"Add the extract book to library" -> "Add extract to library"
"Add extract to the librairy" -> "Import extract" (this one must be short)

**Comment by manuellagrand** [comment]
related to #309
