### ISSUE TITLE
Download from OPDS, lacking notification when achieved

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#289]
There is currently no indication that a download from an OPDS feed has succeeded.

A toast message seems a good solution, with the label "The publication has been imported in the bookshelf" / "La publication a été importée dans la bibliothèque".

**Comment by llemeurfr** [comment]
This must be done also when the user imports and extract, either from the book info window or from the contextual menu in a list.

**Comment by mutterback** [comment]
Example of a potential fix from Microsoft engineer:

https://github.com/felixrieseberg/electron-windows-notifications
npm install --save electron-windows-notifications
 
const appId = 'electron-windows-notifications'
const {ToastNotification} = require('electron-windows-notifications')
 
let notification = new ToastNotification({
    appId: appId,
    template: `<toast><visual><binding template="ToastText01"><text id="1">%s</text></binding></visual></toast>`,
    strings: ['Hi!']
})
 
notification.on('activated', () => console.log('Activated!'))
notification.show()
 
               see also: https://www.microsoft.com/developerblog/2016/10/30/showing-native-windows-notifications-from-electron-using-nodert/

**Comment by mutterback** [comment]
Also adding related user notification issue:

1. Add Catalog URL when device is offline
2. User does not receive any notification 

Better user experience would be
1. Add Catalog URL when device is offline
2. User receives notification: "You need to be connected to the Internet to add an online Catalog" or similar.

**Comment by danielweck** [comment]
Probably related PR: https://github.com/readium/readium-desktop/pull/347

**Comment by danielweck** [comment]
Clicking multiple time on "import extract into library" it indeed not reactive, but in fact behind the scenes the EPUB is added multiple times (until there is finally a confirmation dialog, but at this point it is too late). See screenshot:

![ThoriumMultipleOPDSDownload](https://user-images.githubusercontent.com/625201/59969089-9e20bc80-953d-11e9-8c14-39622bf889a6.png)

**Comment by kevinmainairungu** [comment]
@mutterback working on this from [https://github.com/readium/readium-desktop/pull/347](issue) issue

**Comment by mutterback** [comment]
Checking back on this - it seems incomplete. I now get this unfinished dialog box that needs some user facing text.

Steps to replicate
1. Add a book the My Books from OPDS Catalog
2. Add it again
3. Receive the dialog box

Expected behavior

Dialog box: "This book has already been downloaded to My Books. Do you want to download it again?
![error - dialog](https://user-images.githubusercontent.com/18404465/61242466-c30ae880-a713-11e9-9515-1686423576ec.PNG)

**Comment by danielweck** [comment]
Thank you, I posted a new issue: https://github.com/readium/readium-desktop/issues/431

**Comment by llemeurfr** [comment]
I'll close this issue 
and open a new issue for multiple addition of an ebook from an OPDS feed -> #538
