### ISSUE TITLE
EPUB kusamakura-japanese-vertical-writing.epub not displayed

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#290]
kusamakura-japanese-vertical-writing.epub is an IDPF EPUB 3 sample.  

When I open this book, the page is blank.

**Comment by llemeurfr** [comment]
In the log I find
FATAL WEBVIEW READIUM2_LINK ??!! https://127.0.0.1:8000/pub/L1VzZXJzL2xhdXJlbnRsZW1ldXIvTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0VEUkxhYi5UaG9yaXVtUmVhZGVyL3B1YmxpY2F0aW9ucy80NDE5N2NiYS00MzJhLTRiZDktODM5NC0zMTkzOWY3MTlmNDYvYm9vay5lcHVi/OPS/xhtml/%E8%A1%A8%E7%B4%99.xhtml ==> OPS/xhtml/%E8%A1%A8%E7%B4%99.xhtml

[39980:0614/125209.697079:ERROR:CONSOLE(5509)] "SyntaxError: Unexpected token ' in JSON at position 896445", source: chrome-devtools://devtools/bundled/shell.js

**Comment by danielweck** [comment]
Thank you for reporting this. This is a regression in the URL encoding/decoding routines somewhere in `r2-navigator-js` (Unicode characters in filenames in the zip directory, which is not recommended in EPUB3, but allowed nonetheless).
I filed an issue: https://github.com/readium/r2-navigator-js/issues/40

**Comment by danielweck** [comment]
Fixed in `r2-navigator-js` version `1.0.28`, see https://github.com/readium/r2-navigator-js/issues/40

As usual, the `readium-desktop` PR based on the `develop` branch with the latest `r2-xxx-js` packages and up-to-date minor semantic versioning revisions:
https://github.com/readium/readium-desktop/pull/234

**Comment by llemeurfr** [comment]
closed because fixed in `r2-navigator-js`.
