### ISSUE TITLE
Information button is not functional the first time you read a book

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#292]
Difficult to reproduce. I didn't find stable conditions for it to happen. 

Steps:
- Open a book
- Click on the "book info" button
Sometime, nothing shows up. No specific trace in the log. 
Closing the reading window and opening it again usually works.

**Comment by panaC** [comment]
It appears only for me when you grab a new book.

In first read : information panel isn't available.

**Comment by brettins** [comment]
`this.props.publication` is undefined in `Reader.tsx` for the first opening of the book, which is stopping the "I" button from firing anything. 

Reader.tsx:480
```
    private displayPublicationInfo() {
        if (this.props.publication) {
            this.props.displayPublicationInfo(this);
        }
    }
```

**Comment by manuellagrand** [comment]
I can't reproduce this issue

**Comment by danielweck** [comment]
I can reproduce this bug 100%.
@manuellagrand try this: import a book, click on the cover image to open the reader, click the info button => nothing happens.
