### ISSUE TITLE
Top system menu, change the labels

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#293]
On MacOS, the top menu contains 

Electron
   Quit EDRLab.ThoriumReader
Edit
  Undo, Redo etc. 

We should see only
Thorium Reader
   Quit the application

**Comment by Scarsniik** [comment]
fixed in e5eacbb

**Comment by danielweck** [comment]
Closing, as fixed.

But see:
https://github.com/readium/readium-desktop/issues/390

Also see:
https://github.com/readium/readium-desktop/issues/454
and 
https://github.com/readium/readium-desktop/issues/417
