### ISSUE TITLE
On Windows, the main window can become blank after a windows resize or after some random time

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#294]
This has been only seen on Windows. No indication of the exact conditions.

**Comment by danielweck** [comment]
The "blank window" (white) occasionally happens to me when the application starts. The DOM body content is SVG, so it looks like the UI fails to load.

**Comment by danielweck** [comment]
Follow-up: ah, also in Linux! (random)

**Comment by danielweck** [comment]
I also experience this on MacOS, any time while using the app. Note that this is in development mode, with or without screen reader. I suspect the dev tools may interfere with rendering, so we need to double-check in release/production mode to see if the bug is reproducible,

**Comment by danielweck** [comment]
Apparently there is a similar "flickering" rendering bug with the nav bar at the top, is that correct @llemeurfr ? I have tested in both `npm run start` (production build) and `npm run start:dev` (development build), I am not able to reproduce this bug (not once). Could you please provide some details? (is there an issue already filed for this navbar problem? If so, I cannot find it, sorry)

**Comment by panaC** [comment]
Maybe try with package building. At Laurent and me or on the Windows PC: the problem appears from the beginning, when you click, move on the window.

**Comment by danielweck** [comment]
Ah, I managed to reproduce the nav bar flicker on Windows 10! (using the app deployed on the Store)
I cannot reproduce consistently, but I did notice something interesting: at one point during my tests, the navbar started to blink at regular intervals, exactly at the same frequency as the text cursor inside the search box (in the library view). It happened once, I have not been able to reproduce this.

**Comment by llemeurfr** [comment]
Here is how I get the issue on the navbar: 
- select My Books
- scroll until you see My Tags
- move the mouse up / down several times, from the nav bar to the bottom of the window and back.
-> The nav bar disappears and then reappears / disappears more or less randomly depending on mouse movements.

Note that as soon as we scroll in the My Books screen, the pb will appear: when I start scrolling (barely) and move the cursor to the nav bar, the shadow under the nav bar starts to disappear.

**Comment by llemeurfr** [comment]
fixed by #498.
