### ISSUE TITLE
OPDS feed, implement search

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#296]
In the UI or each OPDS catalog, a search bar is hidden until we develop the OPDS search feature.

This feature relies on the proper processing of search links in OPDS structures. 

Also, when the OPDS search bar is re-activated, the position of the search icon will have to be fixed.

**Comment by llemeurfr** [comment]
In OPDS 1.1, search is defined in https://specs.opds.io/opds-1.1.html#Search. The feature is declared via the presence of an opensearch link in the feed. It is using a templated URL and the "searchTerms" variable. 

Note: We will not use the "atom:author", "atom:contributor" or "atom:title" for the short term, as our search field is generic. 

ex. in https://catalog.feedbooks.com/catalog/public_domain.atom
there is an element <link rel="search" href="https://catalog.feedbooks.com/opensearch.xml" type="application/opensearchdescription+xml" title="Rechercher sur Feedbooks"/>

https://catalog.feedbooks.com/opensearch.xml contains
<Url type="application/atom+xml;profile=opds-catalog;kind=acquisition" template="https://catalog.feedbooks.com/search.atom?query={searchTerms}"/>

https://catalog.feedbooks.com/search.atom?query=gatsby
returns a feed of search results, ready for display. 
 
In OPDS 2, search is currently defined by https://github.com/opds-community/drafts/blob/master/opds-2.0.md#2-search. The syntax is simpler, as the templated URL is directly in the json structure.

**Comment by llemeurfr** [comment]
Here is a sample OPDS 2 feed, with a search feature: https://catalog.feedbooks.com/catalog/index.json

**Comment by Scarsniik** [comment]
fixed in c234373
