### ISSUE TITLE
OPDS Catalog, list view, bad layout for contextual actions

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#297]
Steps:
- open the feedbooks OPDS feed
- move to New Releases
- select the list view
- open the contextual menu associated with The Devil's Slave

![Capture d'écran 2019-06-14 16 47 31](https://user-images.githubusercontent.com/14943186/59517562-24952880-8ec4-11e9-8f1f-104130be674f.png)

The buttons should be horizontally aligned. "Buy this book" should not be in a rectangle (this is an external link, not a button. This link should be after the "Import extract" button.

**Comment by Scarsniik** [comment]
fixed in ecad6e0
