### ISSUE TITLE
Book info partially hidden if the window is small 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#301]
The top of the book info modal window should not be hidden when the app window is resized to a small factor. 

![Capture d'écran 2019-06-14 17 05 40](https://user-images.githubusercontent.com/14943186/59518806-c3bb1f80-8ec6-11e9-82b5-e2da2f2553a5.png)

**Comment by llemeurfr** [comment]
The reason is the presence of the search bar, which is totally unused in this context. Get rid of this search bar here.

**Comment by Scarsniik** [comment]
fixed in 667df5c
