### ISSUE TITLE
Tag added, My Books must reflect the new tag

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#302]
Steps from the My Books view:
- Choose a book
- Open the book info window from the contextual menu
- Add a new tag
- Close the book info window
The tag should appear in the My Books view, which means this view should have been refreshed.

**Comment by llemeurfr** [comment]
Same if a tag is removed from a book. The number of tags should be updated or the tag suppressed from the My Books view.

**Comment by Scarsniik** [comment]
fixed in a57b39b

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/pull/373
