### ISSUE TITLE
keyboard navigation - close a modal using escape

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#304]
The book information modal window cannot be close using the espace key. This would be welcome. 

Currently the user must 'tab' to the close button to do it.

**Comment by Scarsniik** [comment]
fixed in dfeb978

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/349

**Comment by danielweck** [comment]
This was fixed, see comment above.
