### ISSUE TITLE
NVDA issues 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#305]
Narrator issues are treated in another issue, #214.

NVDA support is coming, below is the list of remaining issues on Windows (first in French).

**Comment by manuellagrand** [comment]
- Lorsqu'on met le fenêtre en plein écran il y a une perte du focus qui ne revient pas sur le bouton quitter le fenêtre

- Lors de la navigation dans les catégories "Ajout récent" ou "En cours de lecture" on ne parvient pas à atteindre tout les livres de la catégorie peu importe le sens dans lequel on navigue le dernier élément est sauté, le focus passe automatiquement à la flèche qui permet de faire défilé les livres.

- Lorsqu'on navigue au sein des catégories, on ne sait pas dans quel catégorie se trouve le focus.

- Dans l'onglet "Settings/Préférences" lorsqu'on sélectionne un sous-menu (à l'aide de la touche entrée) on devrait accéder à son menu (actuellement nécessite de naviguer à travers toutes les entrées du sous menu)

- Dans le reader on ne peut modifier la taille de la  police ainsi que sa police, on ne peut pas modifier la taille de la marge, l'espacement entre les mots, l'espacement entre les lettres et l'espacement entre les lignes.

Lorsqu'on souhaite changer de page il y a une perte du focus qui nécessite d'appuyer sur le texte pour pouvoir changer de page. (Windows)

**Comment by Scarsniik** [comment]
I think this issue can be closed. I tested all the case and it was resolved
Only the 3rd is not resolved but navigation should change quickly to resolve the issue #303

**Comment by llemeurfr** [comment]
Remaining issues (potential) will be treated in specific issues.
