### ISSUE TITLE
Thorium icon - the app should get its personal icon

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#306]
We have this icon, in SVG and PNG.

**Comment by llemeurfr** [comment]
![thorium-300](https://user-images.githubusercontent.com/14943186/59522660-860ec480-8ecf-11e9-98da-57c0d5954264.png)

**Comment by llemeurfr** [comment]
ask me for the resolution you need.

**Comment by Scarsniik** [comment]
fixed in ac3a338 and 9c0401e

**Comment by manuellagrand** [comment]
when i open a book, icon of the app is replaced by icon unidentified.

On Ubuntu 16.04

**Comment by danielweck** [comment]
This is fixed, but also see: https://github.com/readium/readium-desktop/issues/394
