### ISSUE TITLE
Windows - My Books window too wide

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#307]
On Windows, there is a sidebar on the bottom of the screen and the window is in fact must too wide. No problem on Mac.

**Comment by Scarsniik** [comment]
fixed in f286291

**Comment by manuellagrand** [comment]
fixed in #316

**Comment by manuellagrand** [comment]
On Ubuntu (version 16.04) the sidebar on the bottom is not present but the window is still too wide when i naviguate with touchpad

**Comment by danielweck** [comment]
Laurent, is this still a problem?

**Comment by llemeurfr** [comment]
@Scarsniik, can you please check on your Linux box?

**Comment by Scarsniik** [comment]
I don't have the problem anymore
