### ISSUE TITLE
Open reading view in full screen if library view is in full screen

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#308]
On a laptop, users will often open the library view full screen. In this case, when they open a book, the reading view must also be full screen (I didn't say "Zen" mode), .

**Comment by panaC** [comment]
Do you mean that reader will have to open with the same resolution of the main windows ?

**Comment by llemeurfr** [comment]
yes it would fulfill the requirement. 

Also, in the case I have 2 screens, even if the library view is on the external screen, ebooks are open on the main screen. Having the reading view really replace the library view, as with iBooks, would be better UX. But only if it's easy.

**Comment by panaC** [comment]
I can try to see that
