### ISSUE TITLE
filter for .epub when adding a book into "My Library" from local drive

### ISSUE THREAD

**Issue by mutterback** [readium/readium-desktop#310]
When you Add Books (+ sign) from My Books, the dialog box that pops up looks for "Custom Files" with the drop down option for "All Files" and does not filter the directory for .epub

Here's the recommended fix:

https://electronjs.org/docs/api/dialog
{
  filters: [
    { name: 'ePub', extensions: ['epub'] }
  ]
}
 
--- so like:
 
const { dialog } = require('electron')
console.log(dialog.showOpenDialog({
  filters: [
    { name: 'ePub', extensions: ['epub'] }
  ]
}
))

**Comment by panaC** [comment]
Hi

It's not a system dialog that is used but an html input file : https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/file

```
                <input
                    id="epubInput"
                    type="file"
                    aria-label={__("accessibility.importFile")}
                    onChange={ this.importFile }
                    multiple
                    accept=".lcpl, .epub"
                />
```

It seems good to me, that accept only lcpl and epub extension.
I don't believe that we can change this with html input file dialog.

What do you think ?

**Comment by mutterback** [comment]
Thank you. I agree, accept only lcpl and EPUB extension. I'm not attached to the technical suggestion from. The user experience is the important issue.

**Comment by panaC** [comment]
@llemeurfr can you close
