### ISSUE TITLE
Cannot show Navigation items in Japanese-vertical-writing

### ISSUE THREAD

**Issue by toshiakikoike** [readium/readium-desktop#328]
Version: v1.0.0-alpha.2(Release Version)
Sample EPUB:
https://github.com/toshiakikoike/epub_file/blob/master/mymedia.epub
Sample Source:
https://github.com/toshiakikoike/epub_file/tree/master/mymedia

Show only one line(title element or first list item), but navigation document has more toc items.
Image:
<img src="https://github.com/toshiakikoike/epub_file/blob/master/readium005.png?raw=true">

navigation document:
https://github.com/toshiakikoike/epub_file/blob/master/mymedia/OEBPS/toc.xhtml

**Comment by danielweck** [comment]
Hello, which application is that? The current UI does not look like this at all :)

**Comment by toshiakikoike** [comment]
Readium Desktop v1.0.0-alpha.2 downloaded from https://github.com/readium/readium-desktop/releases/tag/v1.0.0-alpha.2
(ReadiumDesktop.Setup.1.0.0-alpha.2.exe)
<img src="https://github.com/toshiakikoike/epub_file/blob/master/readium-desktop-nav.png?raw=true">

**Comment by danielweck** [comment]
This is over a year old. I am pretty sure this bug was fixed in later unreleased iterations of the software. I will check.

**Comment by llemeurfr** [comment]
Dear Koike, a new release will very soon be released, with a new design; it is currently under heavy testing and you can compile it from the develop branch of the project. The new version is a beta version, the final 1.0 version should be released in July.

**Comment by toshiakikoike** [comment]
Thank you Daniel and Laurent.
I'll try and test by new version after the final 1.0 version.
