### ISSUE TITLE
Removed publications are not deleted from the filesystem

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#329]
For example on Windows10:
`C:\Users\danie\AppData\Roaming\EDRLab.ThoriumReader\publications\bc908720-7292-4019-b0d0-806fa2ce6258\book.epub`
...or MacOS:
`/Users/danielweck/Library/Application Support/EDRLab.ThoriumReader/publications/b8f0bb5f-f74c-4b30-ad6d-f6845c21df39/book.epub`

=> the cover image (if any), the `book.epub` and the containing folder (UUID) remain in the app-private storage area, so it looks like this Thorium-specific space will grow indefinitely.

**Comment by panaC** [comment]
this is the function to remove the publication : 
```
export function rmDirSync(dirPath: string): void {
    let filenames = [];

    try {
        filenames = fs.readdirSync(dirPath);
    } catch (err) {
        return;
    }

    for (const filename of filenames) {
        const filePath = path.join(dirPath, filename);

        if (fs.statSync(filePath).isFile()) {
            fs.unlinkSync(filePath);
        } else {
            rmDirSync(filePath);
        }
    }

    fs.rmdirSync(dirPath);
}
```

I think that rmdirSync don't remove directory not empty.

I can looking how solve that.

**Comment by panaC** [comment]
Finally the issue doesn't provided from above function, but from a wrong call to a global delete function
