### ISSUE TITLE
Incorrect keyboard tabindex in icon/button group in top-right corner

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#337]
Keyboard tab navigation into these buttons is confusing, partially reversed.

**Comment by panaC** [comment]
![image](https://user-images.githubusercontent.com/3198865/60336924-f6264b80-99a1-11e9-89d0-bf6d213f36ba.png)

**Comment by danielweck** [comment]
PR: https://github.com/readium/readium-desktop/pull/440
