### ISSUE TITLE
EPUB import confirmation dialog is too wide (MacOS)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#339]
![ThoriumDialogWide](https://user-images.githubusercontent.com/625201/59849432-812e9280-935f-11e9-8530-55d13e1a58b6.png)

**Comment by danielweck** [comment]
When the window is resized manually, its dimensions snap to fit the dialog's width (and cannot be reduced further)

**Comment by danielweck** [comment]
Related issue (same cause?): https://github.com/readium/readium-desktop/issues/358

**Comment by panaC** [comment]
It works on Mac os on my side. Have you still the same issue ?

**Comment by danielweck** [comment]
Yes, the issue persists. To reproduce: close Thorium, delete the JSON file that saves the application's window dimensions (`/Users/YOU_USERNAME/Library/Application Support/EDRLab.ThoriumReader/windowRectangle.json`), and start the app. You will see that the window is too narrow for the import dialog (as per the screenshot I posted in the issue description).

**Comment by panaC** [comment]
you're right, I invert height and width per default
