### ISSUE TITLE
UI slider controls can be dragged, but cannot be clicked on track to set value directly

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#342]

**Comment by panaC** [comment]
what do you mean ?

**Comment by danielweck** [comment]
The track of the slider control is very thin, which means that mouse clicking often results in missing the track, and consequently being unable to set the value with a single click.

**Comment by danielweck** [comment]
I am closing this issue. The slider control's track is in fact clickable, but there is a problem with the CSS cursor (pointer, hand icon), which is activated in whole surface areas in the reader view menus (settings, navigation structures).

**Comment by danielweck** [comment]
Re-opening. The bug is: despite a common CSS, the sliders are not consistent depending on their integration context (the height varies, discrepancy between font size and the group of sliders for spacing).

Since the fix for the mouse cursor pointer ( https://github.com/readium/readium-desktop/issues/456 ), the lack of clickable area for the range input is much more obvious.

I have a fix. See the before/after screenshots:

![ThoriumRangeInputBefore](https://user-images.githubusercontent.com/625201/61560054-18702e00-aa63-11e9-8fef-457d326dff8e.png)

![ThoriumRangeInputAfter](https://user-images.githubusercontent.com/625201/61560055-18702e00-aa63-11e9-9016-e125e12b17a8.png)
