### ISSUE TITLE
skip-to-content keyboard accessibility link: should highlight target when clicked (temporary flashing outline)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#346]
Note that this is how the navigator handles document targets. I will see if I can use the same techniques in the UI.

**Comment by Scarsniik** [comment]
fixed in a240094

**Comment by danielweck** [comment]
Pull Request: https://github.com/readium/readium-desktop/pull/447

**Comment by danielweck** [comment]
Note that this issue is about temporarily highlighting (visually-speaking) hyperlink **targets** which are not necessarily tabbable or even focusable, such as a `main` element which contains the content area that a "skip link" would typically reach into.

Such feature would typically rely on the existing CSS `:target` pseudo-class. In fact, there is already a style to achieve this effect:
https://github.com/readium/readium-desktop/blob/758d318ba17c334faeba8097f9b9d457b74d8bba/src/renderer/assets/styles/focus.css#L16-L37

For more context, see my comment:
https://github.com/readium/readium-desktop/pull/447#issuecomment-512846320

What needs to be discussed in this issue is whether such "highlighting" mechanism actually improves accessibility in the context of the Thorium User Interface. This mechanism is used in the EPUB HTML content documents, as it greatly improves usability for sighted users with mouse and keyboard interaction (without the visual effect, the user has now idea where the hyperlink targets are).

This technique is also used in the DAISY accessibility testsuite (albeit, the provided example displays a permanent highlight / outline, whereas I implemented a temporary one in the EPUB navigator):

https://github.com/daisy/epub-accessibility-tests/blob/f04c9d6dd1c4c9275e9f80000b31663fb06b44b2/content/epub30-test-0340/EPUB/Styles/styles.css#L34-L41

**Comment by danielweck** [comment]
Closing, as not necessary in UI (okay in EPUB docs)
