### ISSUE TITLE
display settings (in reader view) should behave like language choice and theme selection (radio with single active option)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#350]
Right now, the column etc. preferences are accessible via keyboard tab navigation, instead of arrow key which is standard practice for radio "buttons"

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/303

**Comment by panaC** [comment]
related to #365

**Comment by danielweck** [comment]
Hello @panaC did you close this issue intentionally? If so, is there a bugfix for it, and could you please link to the corresponding PR? Alternatively, if this is a duplicate, could you please add a message like "closing as duplicate of #xx". Thank you! :)

**Comment by panaC** [comment]
Sorry Daniel,

closing as duplicate of #365

**Comment by danielweck** [comment]
#365 and #350 are two different problems.

**Comment by danielweck** [comment]
Work in Progress in PR: https://github.com/readium/readium-desktop/pull/401
