### ISSUE TITLE
Menu item text "Supprimer Definitivement" too wide on MacOS (line break)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#358]
![ThoriumMenuItemWide_](https://user-images.githubusercontent.com/625201/59966651-39526b80-9517-11e9-98a0-738a828b1453.png)

**Comment by danielweck** [comment]
Related issue (same cause?): https://github.com/readium/readium-desktop/issues/339

**Comment by danielweck** [comment]
Another instance of clipped text in menu items:
![ThoriumClippedMenuText](https://user-images.githubusercontent.com/625201/59969050-cb209f80-953c-11e9-9fdf-6f51ba978197.png)

As a general comment, I noticed excessive verbosity in French and English UI labels. I suggest we do a complete check-over at the next opportunity (lesser priority right now)

**Comment by llemeurfr** [comment]
Supprimer définitivement -> Supprimer
Ajouter l'extrait à la bibliothèque -> Importer

**Comment by danielweck** [comment]
+1 to Laurent's suggestion!
When time allows I will do a complete review pass on the English locale, I think we can use more concise terms. I am not so sure how "compact" other locales can be (especially French tends to be quite verbose), but shorter is usually better :)

**Comment by JayPanoz** [comment]
If I may – been there, done that –, keep in mind German but also Dutch or Danish actually may occasionally be a lot more verbose (and you end up with a ratio of 3:1 from English), so do not hesitate to protect against very lengthy labels (e.g. ellipsis, etc.) in any case.

**Comment by danielweck** [comment]
+1 for ellipsis.
For example https://github.com/readium/readium-desktop/issues/427

**Comment by Scarsniik** [comment]
fixed in 56fb184

**Comment by danielweck** [comment]
PR: https://github.com/readium/readium-desktop/pull/443
