### ISSUE TITLE
"Fiche info" popup dialog is not modal (mouse interaction above the blurred greyed area is allowed)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#359]
Note how I was able to switch to a different menu ("preferences") using the top UI:

![ThoriumModalDialog](https://user-images.githubusercontent.com/625201/59966632-fe503800-9516-11e9-9a24-2f526b524c89.png)

**Comment by danielweck** [comment]
Similar issue in the reader view, here shown with the right-hand-side slide-out menu overlaying the modal dialog.

![ThoriumModalDialogMenuOverlay](https://user-images.githubusercontent.com/625201/59966816-728bdb00-9519-11e9-92bc-04f64c032690.png)

**Comment by panaC** [comment]
related to #370

**Comment by Scarsniik** [comment]
fixed in 416b6ae

**Comment by danielweck** [comment]
Thanks @Scarsniik ! :)
However, if I am not mistaken your fix is only for the library window, could you please check the reader view as well? (see the above screenshot, which shows the slide-out right-hand-side menu incorrectly displaying over the modal popup dialog)

**Comment by danielweck** [comment]
I posted review comments in the PR:
https://github.com/readium/readium-desktop/pull/381

**Comment by Scarsniik** [comment]
Yes, it works with the reader
