### ISSUE TITLE
Library view, horizontal sliders, keyboard tab-navigation should not only reach visible items

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#364]
...instead, tab-navigation should hit every single item in the sequence, and bring into view when necessary (assuming the slider's list of items is not subject to "infinite scrolling"). 
The visual interaction of pressing the left/right button-icons to scroll the slider viewport horizontally (in order to reveal out-of-view items) cannot be used effectively by keyboard users if the number of reachable / focusable items is limited to the visible ones (as this requires going back and forth between the left/right arrows and the actual list items).
Note that a "paginated" UI design would allow such a limitation of the number of visible items at any moment in time, but in this case there would not be any sliding/panning at all, just well-defined numbered ranges of contents (which is less elegant / a bit old-school, but has its merits too).

**Comment by danielweck** [comment]
Another way to look at this is: imagine touch-based interaction, where a horizontal finger swipe reveals items in the panning list, left or right. Structurally, keyboard users (possibly blind, but not necessarily) should have access to the same data set as sighted users. There is no UX justification for restricting access only to the visually-shown / non-clipped items.

**Comment by danielweck** [comment]
Another analogy is a vertically-scrolling web page (or horizontally, for that matter): tab-navigation into hyperlinks isn't limited to currently-visible items. Instead, the whole content is reachable, and the browser "brings into view" the targeted content in order to match keyboard focus.

**Comment by Scarsniik** [comment]
This issue is solved. I don't know wich PR solved it but the list slide when the keyboard user reach an hidden item.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/462

**Comment by danielweck** [comment]
@Scarsniik agreed :) This was fixed by mysterious forces.
