### ISSUE TITLE
Missing UI for EPUB nav epub:type="page-list" (epub:type="pagebreak")

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#368]
For example:

https://idpf.github.io/epub3-samples/30/samples.html#childrens-literature

https://github.com/IDPF/epub3-samples/blob/0b3e80553f509fbdfe591008cd7d1e804b24db54/30/childrens-literature/EPUB/nav.xhtml#L146

**Comment by danielweck** [comment]
See `r2-testapp-js`:
![R2-testapp-PageList](https://user-images.githubusercontent.com/625201/60002374-6d857380-9660-11e9-9fcd-a81657d5761a.png)

**Comment by panaC** [comment]
I think that the page number should be displayed in the bottom slider :

![image](https://user-images.githubusercontent.com/3198865/60446816-76f37a80-9c22-11e9-862d-83eb5d033aab.png)

For now we can access to a specific page without known the page number.
Perhaps we can open an issue with this feature ?

**Comment by llemeurfr** [comment]
@panaC, you're right that if an authored page-list is present in the publication, a "page number" should appear in the navigation timeline. 

It it also useful as an index in the navigation panel (on the right side, on Thorium). It is planned in the design but hidden until page-lists are handled properly via locators.

**Comment by llemeurfr** [comment]
Highly related to #82 (which is about a UI for Page List).

We should have a separate discussion for Page List vs Page Breaks. The former is a navigation list, the latter a set of span in the HTML content. 

Proposal: close this issue in favor of #82 and open a new issue about Page Breaks (which will be related to a previously closed issue).

**Comment by danielweck** [comment]
I agree about closing this and keeping #82

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/pull/1319
