### ISSUE TITLE
OPDS info dialog box, wasted space above

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#370]
![ThoriumWastedTopSpace](https://user-images.githubusercontent.com/625201/60004616-e090e900-9664-11e9-9e7a-2e721c6a8e37.png)

I think once this bug is fixed:
https://github.com/readium/readium-desktop/issues/359

...then modal dialog boxes will overlay the entire window area, and therefore less space will be wasted.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/285

**Comment by panaC** [comment]
It's not the wasted space.
The space under the second top bar menu is the working space.

In this case the modal use all the working space

If we want use all window space: we should design a modal above navbar like this : https://react.semantic-ui.com/modules/modal/

What do you think ?
