### ISSUE TITLE
Build Status link is broken

### ISSUE THREAD

**Issue by rkwright** [readium/readium-desktop#376]
The link to the build status of Readium desktop is broken, apparently because it was migrated from the EDRLab repo and still points at (what is now?) a non-existent repo.

**Comment by panaC** [comment]
changed this :
`[![Build Status](https://travis-ci.org/edrlab/readium-desktop.svg?branch=master)](https://travis-ci.org/edrlab/readium-desktop)`

by :
`[![Build Status](https://travis-ci.org/edrlab/readium-desktop.svg?branch=develop)](https://travis-ci.org/edrlab/readium-desktop)`

it should be working
