### ISSUE TITLE
Ambiguous menu name in Reader

### ISSUE THREAD

**Issue by manuellagrand** [readium/readium-desktop#388]
![image](https://user-images.githubusercontent.com/29514056/60647365-d7aacf00-9e3d-11e9-8c7d-5b04f24d67c2.png)

the book icon is "Table of contents" menu in french translate by  "table des matières" when is read by a screen reader. It can be ambiguous for a user.

"Table of contents" -> "Navigation"
"Table des matières" -> "Navigation"

![image](https://user-images.githubusercontent.com/29514056/60648755-dfb83e00-9e40-11e9-93e6-18df29b0eccf.png)

"Illustrations" -> "Table des Illustrations"
"Illustrations" -> "illustration tables"

**Comment by panaC** [comment]
fixed in #380 and #383

**Comment by llemeurfr** [comment]
More details: this button gives access to the Table of Contents plus (if present) the Table of Illustrations, Bookmarks and Annotations, all being ways to navigate into the document. 
I believe that a simple work "Navigation", even if intriguing at first, will allow visual disabled people to discover easily what is below this menu item.
