### ISSUE TITLE
Horizontal scrolling is not blocked

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#389]
![image.png](https://images.zenhubusercontent.com/5d1a0adb1449416ed898590b/a6821af5-0006-4c0f-83fd-0d3a8ef6c677)

It's a bug or a feature ?

**Comment by danielweck** [comment]
I noticed that too during testing with the keyboard. I am not sure how I managed to scroll sideways, I did not manage to reproduce consistently.

**Comment by Scarsniik** [comment]
fixed in 2f4412d

**Comment by danielweck** [comment]
PR: https://github.com/readium/readium-desktop/pull/439

**Comment by danielweck** [comment]
I am not able to reproduce this bug. Any tips?
(MacOS)
