### ISSUE TITLE
"landmarks" vs. "bookmarks"

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#400]
Issue spawned from: https://github.com/readium/readium-desktop/pull/380#issuecomment-508864841

https://github.com/readium/readium-desktop/blob/23a0b6438f78e3096f6fb808cf46a64127e771f2/src/renderer/components/reader/ReaderMenu.tsx#L80-L84

https://github.com/readium/readium-desktop/blob/23a0b6438f78e3096f6fb808cf46a64127e771f2/src/renderer/components/reader/ReaderMenu.tsx#L156-L192

Related issue: https://github.com/readium/readium-desktop/issues/369

**Comment by danielweck** [comment]
Looking at the current UI, I think there was some confusion about EPUB's 3 major types of *authored* navigation structures:

* table of contents (TOC)
* page list (authored list of `epub:type` page-breaks)
* landmarks (which can be `epub:type` list-of-illustration, etc.)

Then, reading systems add their own "bookmarks" and "annotations" lists, which are *not* authored in the original publications, but added as navigation overlay.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/81

**Comment by llemeurfr** [comment]
The confusion is cleared in #81, with proposed actions.
Let's close this issue then.
