### ISSUE TITLE
LevelDown - PouchDB/LevelDB error at application startup in production mode

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#406]
```
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
```

```
Uncaught Exception:
Error: once called more than once
   at /Applications/Thorium Reader.app/Contents/Resources/app.asar/main.js:41:34698
   at /Applications/Thorium Reader.app/Contents/Resources/app.asar/main.js:16:42984
   at /Applications/Thorium Reader.app/Contents/Resources/app.asar/main.js:41:54481
   at /Applications/Thorium Reader.app/Contents/Resources/app.asar/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:349:18
   at /Applications/Thorium Reader.app/Contents/Resources/app.asar/node_modules/argsarray/index.js:14:18
   at /Applications/Thorium Reader.app/Contents/Resources/app.asar/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:428:16
   at /Applications/Thorium Reader.app/Contents/Resources/app.asar/node_modules/sublevel-pouchdb/lib/index.js:243:9
   at /Applications/Thorium Reader.app/Contents/Resources/app.asar/node_modules/sublevel-pouchdb/lib/index.js:74:13
```

**Comment by panaC** [comment]
only on mac-os

**Comment by danielweck** [comment]
By replacing `nodeEnv !== "production"` with `true` in `webpack.config.main.js` in order to activate the "node externals", the following execution trace is revealed:

```
Uncaught Exception:
Error: once called more than once
    at /Volumes/500GB/Code/readium-desktop/node_modules/pouchdb-core/node_modules/pouchdb-utils/lib/index.js:88:13
    at /Volumes/500GB/Code/readium-desktop/node_modules/argsarray/index.js:14:18
    at /Volumes/500GB/Code/readium-desktop/node_modules/pouchdb-core/lib/index.js:769:14
    at /Volumes/500GB/Code/readium-desktop/dist/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:350:18
    at /Volumes/500GB/Code/readium-desktop/dist/node_modules/argsarray/index.js:14:18
    at /Volumes/500GB/Code/readium-desktop/dist/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:429:16
    at /Volumes/500GB/Code/readium-desktop/dist/node_modules/sublevel-pouchdb/lib/index.js:243:9
    at /Volumes/500GB/Code/readium-desktop/dist/node_modules/sublevel-pouchdb/lib/index.js:74:13
```

**Comment by danielweck** [comment]
I thought this problem was fixed, evidently not:
https://github.com/readium/readium-desktop/pull/323

Seems to be a "known" issue:
https://github.com/pouchdb/pouchdb/issues/7819
https://github.com/pouchdb/pouchdb/issues/7825

I am reverting PouchDB *Core* to `7.0.*` ... let's see.

**Comment by panaC** [comment]
I still have the same issue on my mac

**Comment by danielweck** [comment]
Incroyable!!

I wonder whether this is another NPM-related problem? (depending on versions used)

Note that there are two different versions of LevelDown referenced in the global dependency tree (`package-lock.json`), i.e. the one we specify explicitly in `package.json` via `optionalDependencies` (LevelDown v`5.*.*`) and the one implicitly imported deep into `node_modules` via the PouchDB adapter version `7.0.0` which is also a `optionalDependencies` (LevelDown v`3.*.*`)

References:

https://github.com/readium/readium-desktop/blob/6cf1e1b1f55b39a9a25aa77aac734e2418b8e3a0/package.json#L264

https://github.com/readium/readium-desktop/blob/6cf1e1b1f55b39a9a25aa77aac734e2418b8e3a0/package.json#L265
=>
https://github.com/pouchdb/pouchdb/blob/de99825a418bb5ee62c5feafd0046c217941fa9e/package.json#L39

So far this duplication of two different versions of LevelDown has not caused problems, because the `postinstall` step seems to be building the correct binaries for Electron:

https://github.com/readium/readium-desktop/blob/6cf1e1b1f55b39a9a25aa77aac734e2418b8e3a0/package.json#L16

...to replace the provided "prebuilds":
https://unpkg.com/leveldown@5.1.1/prebuilds/

**Comment by danielweck** [comment]
Suggestion: please `rm -rf node_modules` in your clean local clone of the `develop` branch. Normally, at that point you just `npm install && npm run __postinstall` (which installs dependencies in `node_modules` based on the `package-lock.json` provided in the repository). However, in this test please `rm package-lock.json` and then run the install commands. Then please share the output of `npm --version && node --version` and `git --no-pager diff package-lock.json`. Also try to run the app in production mode (not packaged) with `npm run start`. Thanks!

**Comment by panaC** [comment]
always the same

```
> npm --version && node --version && git --no-pager diff package-lock.json
6.9.0
v10.16.0
```

**Comment by danielweck** [comment]
So the `package-lock.json` diff is clear after you `rm package-lock.json && rm -rf node_modules && npm install`??
Interesting...

**Comment by danielweck** [comment]
Another thing to try: `sudo npm cache clean --force` (before initializing NPM deps and re-installing them)

**Comment by danielweck** [comment]
Culprit?
https://github.com/readium/readium-desktop/blob/12fdd5d68ebb2035fdfcd3fdbc4c72f3ee54c61f/src/package.json#L37

**Comment by danielweck** [comment]
Hotfix: https://github.com/readium/readium-desktop/commit/877e2fee1280535bbc14e03094298a80ab998fd0

**Comment by danielweck** [comment]
`npm run package:mac && cd release/mac/Thorium\ Reader.app/Contents/Resources && npx asar e app.asar ex && cat ex/node_modules/pouchdb-adapter-leveldb/package.json | grep -i VERSION`
=>
`7.0.0`

**Comment by danielweck** [comment]
Follow-up: https://github.com/readium/readium-desktop/issues/496

**Comment by danielweck** [comment]
For what it's worth, I posted an issue in the LevelDown tracker:
https://github.com/Level/leveldown/issues/686
