### ISSUE TITLE
Labels: book info: missing label for catalog.addTeaser (all languages)

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#413]
<img width="767" alt="Capture d'écran 2019-07-11 15 56 24" src="https://user-images.githubusercontent.com/14943186/61057717-233d1a00-a3f6-11e9-94c3-f0129d96656f.png">

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/397
