### ISSUE TITLE
Windows, Linux: verify that copy/cut/paste, undo/redo, close-window keyboard shortcuts work without menu items

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#417]
See:
https://github.com/readium/readium-desktop/issues/390

We should also check CTRL+W ALT+F4 for closing windows and/or application.

FYI:
https://electronjs.org/docs/tutorial/keyboard-shortcuts
https://electronjs.org/docs/api/global-shortcut

**Comment by manuellagrand** [comment]
I tested copy/cut/paste and undo/redo on Windows, it works normally.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/454

**Comment by panaC** [comment]
can we close this ?

**Comment by danielweck** [comment]
Checklist to close this issue (both Windows and Linux, both dev and release modes):

1) Undo `CTRL`+`Z` / Redo `SHIFT`+`CTRL`+`Z` (or `CTRL`+`Y`) => test with the search box / text input field.
2) Cut `CTRL`+`X` / Copy `CTRL`+`C` / Paste `CTRL`+`V` => also test with the search box / text input field.
3) Close window `ALT`+`F4` and/or `CTRL`+`W` => test with library and reader windows, and with the web inspectors in debug mode.

**Comment by panaC** [comment]
Undo CTRL+Z / Redo SHIFT+CTRL+Z (or CTRL+Y) => test with the search box / text input field. -> OK

Cut CTRL+X / Copy CTRL+C / Paste CTRL+V => also test with the search box / text input field. -> OK

Close window ALT+F4 and/or CTRL+W => test with library and reader windows, and with the web inspectors in debug mode. -> OK with ALT-F4

on windows

**Comment by danielweck** [comment]
Thanks Pierre! Closing.
