### ISSUE TITLE
Need notification for invalid OPDS feed

### ISSUE THREAD

**Issue by mutterback** [readium/readium-desktop#418]
Steps to repeat:
![OPDS feed loading error](https://user-images.githubusercontent.com/18404465/61086710-9730ef80-a401-11e9-9cd1-8ef26374623e.PNG)

1. Go to Catalogs
2. Type in a URL. Use an invalid URL or a non OPDS URL, for example www.google.com
3. Name the feed, for example "Google" click ADD
4. Feed name is added as a large Blue Box
5. Click on the feed blue box 
6. The spinning circle continues endlessly. See screen shot.

**Comment by kevinmainairungu** [comment]
when i run `npm run start:dev` or `npm start` the information text is displayed.
![Screenshot (20)](https://user-images.githubusercontent.com/23236275/61118851-48876200-a4a2-11e9-98ce-ffb98e23556e.png)
![Screenshot (21)](https://user-images.githubusercontent.com/23236275/61118852-491ff880-a4a2-11e9-8604-27490e4e0ba3.png)

But this is missing once i use `npm run package` to create a nsis package.
