### ISSUE TITLE
Adding or Attempting to Access an OPDS feed while offline results in endless spinning circle

### ISSUE THREAD

**Issue by mutterback** [readium/readium-desktop#419]
Related to https://github.com/readium/readium-desktop/issues/418

If user is offline attempting to access an OPDS feed results in the endless spinning circle (see screen shot, attached.) 

Similarly, you can add a URL, name the URL, create a blue box "catalog" before getting any feedback while offline. When the user clicks the blue box catalog, the endless spinning circle appears.

I recommend that an error message be added when the user clicks on "Catalogs" if the device is offline. For example:

The Catalogs feature requires an Internet connection. Please try again when your device is online. All books in My Books can be read offline. [Return to My Books] button

![OPDS feed loading error](https://user-images.githubusercontent.com/18404465/61088377-440d6b80-a406-11e9-98c9-215f6ed09907.PNG)

**Comment by llemeurfr** [comment]
see also #418
