### ISSUE TITLE
Information tab doesn't show description of Thorium in production+packaged mode

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#422]
Information tab show no Thorium app description in any language.

![information](https://user-images.githubusercontent.com/3198865/61125327-d7e44380-a4a9-11e9-8454-8b23d2db73c4.PNG)

**Comment by kevinmainairungu** [comment]
When I run `npm run start:dev` or `npm start` i get the inforamtion.
![Screenshot (20)](https://user-images.githubusercontent.com/23236275/61128409-737db000-a4ba-11e9-9747-7f83fb29230e.png)
but if i create run `npm run package` to create a nsis package, the information page has no details.
