### ISSUE TITLE
Library view text is misaligned when displaying list (overflow, line wrap)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#427]
When the text has enough horizontal space to expand:

![ThoriumLibraryListAlign2](https://user-images.githubusercontent.com/625201/61211622-f5a6e800-a6f7-11e9-9d72-65e7b95f5e79.png)

**Comment by danielweck** [comment]
When the window width is reduced, the text reflows and line-wraps (the the rightmost column), causing the other columns' content to misalign:

![ThoriumLibraryListAlign1](https://user-images.githubusercontent.com/625201/61211639-0192aa00-a6f8-11e9-8dac-73ddf852dbf4.png)

**Comment by danielweck** [comment]
Suggestion: row height should be locked to a fixed dimension, text should have ellipsis / crop (this will prevent really long titles or author names to mess-up the layout)

**Comment by Scarsniik** [comment]
fixed in 1c42a18

**Comment by danielweck** [comment]
PR: https://github.com/readium/readium-desktop/pull/442
