### ISSUE TITLE
`deLang.json` is missing (`enLang.json` and `frLang.json` ok)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#430]
https://github.com/readium/readium-desktop/blob/541e48bbe45407a8918018e0076d4ca5ebecd68b/src/common/services/translator.ts#L15

https://github.com/readium/readium-desktop/tree/develop/src/resources/locales

**Comment by danielweck** [comment]
Possible source:
https://github.com/haliaeetus/iso-639

**Comment by panaC** [comment]
Where is the source for 'enLang' and 'frLang' ?

**Comment by danielweck** [comment]
No idea. @Scarsniik ?

**Comment by Scarsniik** [comment]
I made a python script to parse csv from wikipedia pages and used it with the fench and english pages

**Comment by llemeurfr** [comment]
It would be good to have the script saved in the 'scripts' folder of the project.

**Comment by panaC** [comment]
We can use this package : https://github.com/michaelwittig/node-i18n-iso-countries
It seems great with a last commit yesterday and 287stars
Or we can just extracts the json files from this package.

**Comment by danielweck** [comment]
Yep, or https://github.com/haliaeetus/iso-639
(there are a few reliable sources)

**Comment by danielweck** [comment]
Note that this PR moves the locale names into a different folder: https://github.com/readium/readium-desktop/pull/506

**Comment by danielweck** [comment]
PR https://github.com/readium/readium-desktop/pull/506 has been merged, see new folder location for locale names: https://github.com/readium/readium-desktop/tree/develop/src/resources/locale-names

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/519

**Comment by panaC** [comment]
https://github.com/haliaeetus/iso-639 and https://github.com/michaelwittig/node-i18n-iso-countries doesn't allow to get back the language translation from locale code.

I try to use this package https://www.npmjs.com/package/cldr, but it need access to CLDR XML files. This file can't be opened from renderer

**Comment by panaC** [comment]
@Scarsniik  Can you make the same things with your parser for DE ? 
I think you have the best solution

https://de.wikipedia.org/wiki/Liste_der_ISO-639-1-Codes

**Comment by danielweck** [comment]
@Scarsniik
> I made a python script to parse csv from wikipedia pages and used it with the fench and english pages

@llemeurfr 
> It would be good to have the script saved in the 'scripts' folder of the project.

+1 :)

https://github.com/readium/readium-desktop/tree/develop/scripts

**Comment by Scarsniik** [comment]
Fixed by #647
