### ISSUE TITLE
Language preference not saved when app is restarted

### ISSUE THREAD

**Issue by kevinmainairungu** [readium/readium-desktop#435]
The language preference is not saved once app is restarted.

Steps to Reproduce:
1.	Launch the application.
2.	Select ‘Settings”.
3.	Select “French”.
4.	Close the application.
5.	Launch the application

**Comment by danielweck** [comment]
Thank you for reporting.
I thought persistence was already implemented, as part of this PR:
https://github.com/readium/readium-desktop/commit/024dc4e64c645dc150432a232e0b65912dcb10d6

It looks like the locale configured in the store is not persistent / saved into DB. To be investigated.

**Comment by danielweck** [comment]
`store.dispatch(setLocale(lang));`
=>
We seem to already have everything in place in the Redux actions:
https://github.com/readium/readium-desktop/blob/develop/src/common/redux/actions/i18n.ts

(search for all occurrences of `ActionType.Set` to find the code paths)

**Comment by danielweck** [comment]
I think there is a typo in the Redux reducer:
https://github.com/readium/readium-desktop/blob/877e2fee1280535bbc14e03094298a80ab998fd0/src/common/redux/reducers/i18n.ts#L23-L26
(missing `i18n` key, should be `state.i18n.locale`)

**Comment by kevinmainairungu** [comment]
@danielweck thank you for the update.

**Comment by kevinmainairungu** [comment]
@danielweck kindly when are you going to make changes to this? Merge fix.

**Comment by danielweck** [comment]
Work in Progress...
https://github.com/readium/readium-desktop/pull/436/files

**Comment by kevinmainairungu** [comment]
@danielweck thanks
