### ISSUE TITLE
Debounce util in this source code?

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#437]
Just wondering:

https://github.com/readium/readium-desktop/blob/develop/src/utils/debounce.ts

Introduced by this PR:

https://github.com/readium/readium-desktop/pull/312

@panaC 
What was the motivation for copy-pasting their TS source into the Thorium codebase? Do we need a specific code tweak or API change?

Or can we just reference the original NPM package?

https://www.npmjs.com/package/ts-debounce
=>
https://github.com/chodorowicz/ts-debounce

**Comment by panaC** [comment]
I'm inspired from this but it's not the same

**Comment by danielweck** [comment]
> I'm inspired from this but it's not the same

I see. What are the changes you made to https://github.com/chodorowicz/ts-debounce ?

**Comment by panaC** [comment]
I added a promise compatibility

**Comment by danielweck** [comment]
Promise debouncer: https://github.com/sindresorhus/p-debounce
