### ISSUE TITLE
When tag added or removed from bookshelf view (publication info popup modal dialog), tag state not reflected in reader view(s)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#450]
The only way to synchronize the tags in the reader view(s) for a given publication is to close it/them, and re-open.

![ThoriumInfoBoxLibrary](https://user-images.githubusercontent.com/625201/61483607-16d83480-a995-11e9-88c9-4f023b38e85d.png)
![ThoriumInfoBoxReader](https://user-images.githubusercontent.com/625201/61483609-16d83480-a995-11e9-82e3-b04d2da53ea7.png)

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/451

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/457

**Comment by Scarsniik** [comment]
Fixed in PR #466
