### ISSUE TITLE
When publication tag added or removed from reader view, tag state not immediately reflected in bookshelf view's own publication info popup modal dialog

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#451]
The only way to synchronize the tags in the bookshelf view is to close the popup modal dialog (publication info box), and reopen it.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/450

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/457

**Comment by Scarsniik** [comment]
Fixed in PR #466
