### ISSUE TITLE
Import notification text shows charcodes (unicode escape sequences)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#453]
For example, test with this EPUB (`'` => `&#39;`):

https://github.com/IDPF/epub3-samples/blob/0b3e80553f509fbdfe591008cd7d1e804b24db54/30/childrens-literature/EPUB/package.opf#L8

https://idpf.github.io/epub3-samples/30/samples.html#childrens-literature

![ThoriumImportText](https://user-images.githubusercontent.com/625201/61488416-12fddf80-a9a0-11e9-95c3-829e2650cf90.png)

**Comment by Scarsniik** [comment]
fixed by #552
