### ISSUE TITLE
MacOS: Apple key + W does not close windows

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#454]

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/417

**Comment by danielweck** [comment]
I added a note in the PR https://github.com/readium/readium-desktop/pull/483

Copied here:

The solution is to re-instate the typical "window" menu which has built-in accelerator shortuts, i.e. `role: "close"`, `role: "front"`, `role: "minimize"`, `role: "togglefullscreen"`, etc. and for MacOS (darwin) also in the first "about" menu `role: "services"`, `role: "hide"`, `role: "hideothers"`, `role: "unhide"`, `role: "quit"`.

See:
https://electronjs.org/docs/api/menu#examples

**Comment by llemeurfr** [comment]
PR #483 has been closed because the provided solution was incorrect. Let's try again.
