### ISSUE TITLE
When publication tags edited from reader view, tag state in library is completely overriden

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#457]
1) library view: open publication X
2) reader view: detach, place the 2 windows side by side
3) library view: add "test-library" tag to publication X (close dialog, scroll down to confirm tag exists)
4) reader view: (note that the "test-library" tag is not shown, this is issue https://github.com/readium/readium-desktop/issues/450 ) add "test-reader" tag
5) library view: notice how "test-library" has disappeared, replaced with tag state from reader view ("test-reader" tag)
6) reader view: add/remove tags and observe state update at the bottom of the library view

**Comment by danielweck** [comment]
Related issues:
https://github.com/readium/readium-desktop/issues/450
https://github.com/readium/readium-desktop/issues/451

**Comment by Scarsniik** [comment]
Fixed in PR #466
