### ISSUE TITLE
is the lcp file imported ?

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#460]
![Screenshot 2019-07-22 at 11 06 10](https://user-images.githubusercontent.com/3198865/61620270-d6b4d280-ac70-11e9-8708-3c7de809575d.png)

```
    public async importFile(filePath: string, isLcpFile?: boolean): Promise<PublicationDocument> {
        const ext = path.extname(filePath);

        if (ext === ".lcpl" || (ext === ".part" && isLcpFile)) {
            return this.importLcplFile(filePath);
        } else if (ext === ".epub" || (ext === ".part" && !isLcpFile)) {
            return this.importEpubFile(filePath);
        }

        return null;
    }
```

**Comment by panaC** [comment]
they do not imports lcp files.

Should you remove `isLcpFile: boolean` to automatically check the extname ?
or making an external verification to send in parameter  ?

**Comment by danielweck** [comment]
This optional function argument is here to address the edge-case of files with the `*.part` extension (progressive download, not renamed after finish) acquired from an OPDS feed:

https://github.com/readium/readium-desktop/blob/3703a8a0ac0250e3f83a5d854f56f8a08e73826e/src/main/services/catalog.ts#L160-L170

https://github.com/readium/readium-desktop/blob/3703a8a0ac0250e3f83a5d854f56f8a08e73826e/src/main/services/catalog.ts#L141-L146

**Comment by danielweck** [comment]
Does this issue / question need to remain open?
