### ISSUE TITLE
OPDS feeds, implement pagination

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#462]
Many OPDS feeds are paginated. We have the choice between two implementations:
1- simple Next / Previous links
2- infinite scroll.

The choice will be based on the difficulty of implementation and difficulty of making it accessible.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/364

**Comment by danielweck** [comment]
Also applies to OPDS search results.
