### ISSUE TITLE
OPDS feeds, set Accept-Language

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#463]
Some OPDS feeds (e.G. Feedbooks) use the http Accept-Language property to select a localized feed for the user. 

Accept-Language should be set to the language chosen by the user in the app.

**Comment by panaC** [comment]
cf https://edrlab.slack.com/archives/C5XBK781X/p1563876322001200

**Comment by danielweck** [comment]
Point of interest: note that in the LCP / LSD HTTP interactions implemented by `r2-lcp-js`, `Accept-Language` is currently set to `en-UK,en-US;q=0.7,en;q=0.5`. This can be useful to get error messages in the user locale, but I am personally not aware of any LCP/LSD server that implements language negotiation, at this point in time.
