### ISSUE TITLE
deprecation warning about Buffer API

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#464]
```
$ ./Thorium\ Reader.exe read "feu"

(node:4328) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2018, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:1:9428)
    at C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:1:27617
    at C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:1:27668
    at At (C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:1:27958)
    at Lt (C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:1:28335)
    at Ot (C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:1:28417)
    at i (C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:1:6267)
    at q (C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:29:17773)
    at Object.<anonymous> (C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:29:13657)
    at Generator.next (<anonymous>)
    at a (C:\Users\offic\pierre\thorium\release\win-unpacked\resources\app.asar\main.js:16:1417)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

when I execute thorium with cli command read

**Comment by danielweck** [comment]
Yes, the Moment warning message comes from date/time syntax which is used in the imported/loaded publication (EPUB metadata, most likely), or OPDS feed. There is nothing we can do, as we side-load arbitrary content which may contain errors / innacuracies.

http://momentjs.com/guides/#/warnings/js-date/

**Comment by danielweck** [comment]
Regarding the Buffer() constructor warning: yes, there are several instances in the Thorium/Readium code where this deprecated method of construction is used.

**Comment by panaC** [comment]
Can we not hide this moment warning ?

The slack trace must not be see to user

**Comment by danielweck** [comment]
I do not know. See:
https://github.com/moment/moment/blob/96d0d6791ab495859d09a868803d31a55c917de1/src/lib/create/from-string.js#L222

**Comment by danielweck** [comment]
We can use `suppressDeprecationWarnings`:
https://github.com/moment/moment/blob/96d0d6791ab495859d09a868803d31a55c917de1/src/lib/utils/deprecate.js#L6-L9

**Comment by panaC** [comment]
fix with #487 #485

**Comment by danielweck** [comment]
Yes, the `Buffer` API usage was indeed fixed in https://github.com/readium/readium-desktop/pull/487 , but also indirectly in `r2-navigator-js` which accounted for many of the deprecation messages (see https://github.com/readium/r2-navigator-js/commit/eb455a6a27e7d8354c55e3a12aa3ebb5eccfdd85 )

**Comment by danielweck** [comment]
However, I do not understand how https://github.com/readium/readium-desktop/pull/485/files relates to this issue? Could you please explain? Is it related to `Moment` or to `Buffer`?

**Comment by panaC** [comment]
both, moment use console.info no ?
I doesn't see how to fix this else

**Comment by danielweck** [comment]
https://github.com/readium/readium-desktop/issues/464#issuecomment-514294302

**Comment by panaC** [comment]
of course I tried that, no ?

**Comment by danielweck** [comment]
As I explained in this comment https://github.com/readium/readium-desktop/issues/464#issuecomment-514290506 the `Moment` deprecation warning is due to parsing an obsolete string syntax, typically when handling OPDS or EPUB metadata (which we have no control over, because the very nature of a reading system is to side-load third-party arbitrary content).

Thankfully, `Moment` offers the `suppressDeprecationWarnings` API so we can ignore these annoying messages. Note that this message would actually be really useful in cases where we would be in control of the string syntax, as this would flag our code appropriately. But our usage of `Moment` means we have to ignore the deprecation warnings.

**Comment by panaC** [comment]
if you can, I'll let you do it.. suppressDeprecationWarnings is not typed, it seems to me

**Comment by danielweck** [comment]
> moment use console.info no ? I doesn't see how to fix this else

I'm not sure what you mean. `Moment` is a date/time utility library. The PR that disabled `console` in production / packaged mode was aimed at reducing shell message output, right?

**Comment by panaC** [comment]
idk, thanks Daniel

**Comment by danielweck** [comment]
Closing: the `Buffer` API usage was fixed in https://github.com/readium/readium-desktop/pull/487 , and via `r2-navigator-js` which accounted for many of the deprecation messages (see https://github.com/readium/r2-navigator-js/commit/eb455a6a27e7d8354c55e3a12aa3ebb5eccfdd85 )
