### ISSUE TITLE
sigsegv on windows only at the end of thorium execution

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#465]
```
$ ./Thorium\ Reader.exe

Segmentation fault

```

The seg fault appear when I launch a command on cli with or without main window.
But on `$ ./Thorium\ Reader.exe --help` they are no segv

I have already test with the latest pouchdb-adapter-leveldb version: It's same effect.

**Comment by danielweck** [comment]
Is that specific to this PR? https://github.com/readium/readium-desktop/pull/403

**Comment by panaC** [comment]
No with or without cli, it's segfault

**Comment by danielweck** [comment]
Oh wow okay! That's "interesting" :)
So you are able to reproduce this bug on the `master` branch?

**Comment by llemeurfr** [comment]
The issue does not appear anymore. Let's close it for now.
