### ISSUE TITLE
Skip button / link: move to upper-left

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#470]
GitHub, top-left corner button-link overlay:
https://github.com

Mozilla MDN, full horizontal top-aligned button-link overlay:
https://developer.mozilla.org/en-US/

Issue discovered when dealing with PR proposal:
https://github.com/readium/readium-desktop/pull/447

**Comment by llemeurfr** [comment]
Let's use the Github way, top-left, blue rectangle (<-> a&&Y focus), white text. 

<img width="429" alt="Capture d'écran 2019-07-24 14 08 34" src="https://user-images.githubusercontent.com/14943186/61792233-9003db80-ae1c-11e9-8dd8-2ca24ca66565.png">

**Comment by Scarsniik** [comment]
fixed in #551
