### ISSUE TITLE
what about lsdStatus.link in utils/lcp.ts

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#484]
https://github.com/readium/readium-desktop/blob/b2f673a8e31f54f8319a0232db952fe698cb2ef1/src/utils/lcp.ts#L58-L73

lsdResponse.body returns string type.

however links 'key' is required on lsdStatus.

The lsdResponse.body has an another type that string ?

related to #481

**Comment by danielweck** [comment]
The LCP/LSD code is a little bit out of date, and sometimes erroneous (as per the issues already filed in this GitHub tracker). For example, there is a strongly-typed LSD model, raw JSON "object" / TypeScript `any` should be avoided.
https://github.com/readium/r2-lcp-js/blob/develop/src/parser/epub/lsd.ts

I am assigning the LCP/LSD issues to myself.
