### ISSUE TITLE
In library view, list mode (no cover images), opening a publication requires using the menu, then about box, then read button (should be direct mouse click / keyboard select on the row item)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#497]
![ThoriumLibraryBookOpen1](https://user-images.githubusercontent.com/625201/62203238-a5c85200-b382-11e9-8037-f78ba2e95c04.png)

![ThoriumLibraryBookOpen2](https://user-images.githubusercontent.com/625201/62203249-a7921580-b382-11e9-9d0e-ee37138089b1.png)

**Comment by Scarsniik** [comment]
fixed in #548
