### ISSUE TITLE
library view: "my books" button missing when returning back from "router path" link/segment (ok with back arrow)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#500]
![ThoriumLibraryBack_1](https://user-images.githubusercontent.com/625201/62209026-5b4dd200-b390-11e9-99e2-0c17332fe98b.png)

![ThoriumLibraryBack_2](https://user-images.githubusercontent.com/625201/62209029-5db02c00-b390-11e9-8f87-56f2f1ec4ba4.png)

![ThoriumLibraryBack_3](https://user-images.githubusercontent.com/625201/62209041-66086700-b390-11e9-861d-9ca02d7fc784.png)

![ThoriumLibraryBack_4](https://user-images.githubusercontent.com/625201/62209045-69035780-b390-11e9-9391-96f0d6537f90.png)

**Comment by panaC** [comment]
I can't reproduce this bug

**Comment by danielweck** [comment]
Correct, I am not able to reproduce in the develop branch either. I tested the OPDS "search" PR, using a merge of the latest develop branch commit, and the bug occurred!

Issue moved there: https://github.com/readium/readium-desktop/pull/386#issuecomment-516828252
