### ISSUE TITLE
OPDS / catalog view: trailing path item is "Catalogs" (should not be there at all)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#502]
![ThoriumOPDSpath](https://user-images.githubusercontent.com/625201/62209517-b502cc00-b391-11e9-9828-8cf084076b6f.png)

**Comment by panaC** [comment]
not for me

![Screenshot 2019-07-31 at 13 55 41](https://user-images.githubusercontent.com/3198865/62209844-f8156d00-b39a-11e9-835f-e012f0cffd5b.png)

**Comment by danielweck** [comment]
Thank you for double-checking this Pierre, you are correct! (I am moving these issues to the PR that introduces the bugs)

**Comment by danielweck** [comment]
Moved to: https://github.com/readium/readium-desktop/pull/386#issuecomment-516819839
