### ISSUE TITLE
OPDS / catalog view: back arrow does not work

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#503]
![ThoriumOPDSBack](https://user-images.githubusercontent.com/625201/62209576-debbf300-b391-11e9-8d5b-e4cd444d8562.png)

**Comment by panaC** [comment]
It's works for me

**Comment by danielweck** [comment]
Thank you for double-checking this Pierre, you are correct! (I am moving these issues to the PR that introduces the bugs)

**Comment by danielweck** [comment]
Moved to: https://github.com/readium/readium-desktop/pull/386#issuecomment-516819999
