### ISSUE TITLE
padding in Bookmark menu

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#507]
![Screenshot 2019-07-31 at 15 32 16](https://user-images.githubusercontent.com/3198865/62216121-79bfc780-b3a8-11e9-9d79-33bb83a8b10f.png)
![Screenshot 2019-07-31 at 15 33 26](https://user-images.githubusercontent.com/3198865/62216179-8fcd8800-b3a8-11e9-9d69-7390a0896e6f.png)

to reproduce click twice on bookmarks icon

**Comment by danielweck** [comment]
I am not able to reproduce, could you please double-check the develop branch? Thanks! :)

**Comment by panaC** [comment]
add a bookmark and remove it: the padding stay in bottom

But the original bug has been fixed

**Comment by danielweck** [comment]
Indeed, I can see the zombie padding when deleting the bookmark, which is removed when another section is opened.
