### ISSUE TITLE
[reader] theme in a publication does not apply everywhere

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#508]
![Screenshot 2019-07-31 at 15 36 30](https://user-images.githubusercontent.com/3198865/62216523-32860680-b3a9-11e9-8c5f-46fa7d53e5cb.png)
![Screenshot 2019-07-31 at 15 38 58](https://user-images.githubusercontent.com/3198865/62216610-58aba680-b3a9-11e9-828f-fd7d14a6ba5c.png)

[H.+G.+Wells+-+The+Time+Machine.epub.zip](https://github.com/readium/readium-desktop/files/3452099/H.%2BG.%2BWells%2B-%2BThe%2BTime%2BMachine.epub.zip)

**Comment by danielweck** [comment]
Could you please post this issue in the ReadiumCSS project?
Thanks! :)
https://github.com/readium/readium-css/issues

**Comment by llemeurfr** [comment]
See https://github.com/readium/readium-css/issues/68
