### ISSUE TITLE
define an _APP_NAME in reader.tsx

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#510]
https://github.com/readium/readium-desktop/blob/c9858d73be67e8f0a0c70c9c1ae1a1f0e2343c22/src/renderer/components/reader/Reader.tsx#L382

_APP_NAME is already declared from the PR CLI https://github.com/readium/readium-desktop/blob/6f79a51b42c05b435c62b0339530a6ace01d8958/webpack.config-preprocessor-directives.js#L32

**Comment by danielweck** [comment]
Also see:
https://github.com/readium/readium-desktop/issues/511

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/commit/de8e69b2513c67adacf5b4b3bf3dcdf8cb2132ee
