### ISSUE TITLE
is it normal to be able to highlight the text in the application ?

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#525]
![Screenshot 2019-08-05 at 15 23 24](https://user-images.githubusercontent.com/3198865/62467891-17ded380-b795-11e9-9c6a-aafd5ec55db6.png)

discord, deezer music, slack, .. doesn't allow to highlight the text layout

**Comment by danielweck** [comment]
Suggestion: CSS `user-select: none` except for publication metadata (information modal popup dialog box), and except for error/warning messages that users could copy/paste when sending bug reports.
