### ISSUE TITLE
Disable the possibility to download a book multiple times from an OPDS feed

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#538]
Steps: 
- open an OPDS feed and select a free book. 
- Select "Add book to library" ->  a toast message appears
- Immediately select "Add" again -> a new toast message appears. 

Once the action has been taken into account, a second action should be blocked until the end of the import. 

After the first import has been achieved, if the user selects a new import of the same book (and this is a generic rule) a dialog box should appear: "This book has already been imported. Do you want to download it again? Yes/No".

If it is complex to record that an import is active and not finished (transient state), the second rule should at least apply (consider that the book is in the DB as soon as its import has begun). 

See also #289 where this issue arised first.

**Comment by Scarsniik** [comment]
There is already the second rule
![image](https://user-images.githubusercontent.com/15014810/62944131-564f4080-bddc-11e9-8748-8390dc8f8c23.png)

Or do you think about something else ?

**Comment by llemeurfr** [comment]
Pas pour la première partie de la demande : pour l'instant rien n'empêche un second téléchargement PENDANT le premier (via un second clic dans la seconde). 

Mais en effet une fois le 1er chargement achevé, la modale actuelle est parfaite, je ne l'avais pas repéré.

**Comment by Scarsniik** [comment]
fixed by #646
