### ISSUE TITLE
Move from chapter to chapter

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#565]
In the Reading view, for a blind person, the left and right keys and arrows (which move from page to page or from screen to screen in scroll view) don’t mean anything (the screen reader reads the whole resource). 
They would prefer a direct action for moving to the next/previous chapter (i.e. resource). And sighed people prefer the arrow keys are currently designed and are ready to use the timeline or ToC to move to another chapter. 

Therefore we need keyboard shortcuts for moving to next/previous chapters. These will be known from blind people, but there will be no equivalent visual button in the Reading View. 

There is not such key defined in https://github.com/readium/readium-js-viewer/wiki/Keyboard.
Ctrl+Left/right Arrows are already taken by JAWS/NVDA for previous/net Word.
Up/Down Arrows for prev/next line.
(source http://www.daisy.org/daisypedia/adobe-digital-editions-overview-and-accessibility-tips)

Proposal: like AZARDI, use Shift Right Arrow or Shift PgUp and Shift Left Arrow or Shift PgDn
source: http://www.daisy.org/daisypedia/azardi-epub-reader-windows

See also #155

**Comment by panaC** [comment]
@danielweck I'm discovering the code base of the reader, and I think this question is more for you,
I'm looking for an api on R2-Navigator to access the previous / next chapter.
I found access to the following page:
https://github.com/readium/r2-navigator-js/blob/4aa590611303fe6b7dd62330aaca3e042180e33a/src/electron/renderer/location.ts#L175-L190

Can you create a new browser function to get the previous / next section?

What do you think ?
How would you do that ?

**Comment by danielweck** [comment]
Generally-speaking there is some API documentation here:
https://github.com/readium/r2-navigator-js/blob/develop/README.md#programmer-documentation

...but I agree with Laurent, I will take on this task assignment.

**Comment by danielweck** [comment]
Note: this has been implemented with `CTRL`+`SHIFT`+`RIGHT/LEFT-ARROW`
