### ISSUE TITLE
OPDS search, "empty" string in locale

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#567]
Hello @Scarsniik 
1) What is the role of the litteraly-empty string `""` in the locale JSONs?
See:
https://github.com/readium/readium-desktop/blob/de9278c77bde0db3f44a54ba84806ca5cf136c5d/src/resources/locales/en.json#L114
...which was introduced in the "OPDS search" Pull Request:
https://github.com/readium/readium-desktop/pull/386
2) Whenever you update the locale JSONs, please invoke the following sequence of commands in order to ensure a clean l10n "state" (no missing keys, no redundant keys, canonical JSON syntax, and strong TypeScript typings):

* `npm run i18n-sort && git diff`
* `npm run i18n-scan && git diff`
* `npm run i18n-typed && git diff`

**Comment by Scarsniik** [comment]
Hello, it's for the message displayed when the result of the search is empty. I agree that the name is not easy to understand. Do you want I change it for something better ?

**Comment by llemeurfr** [comment]
"emptySearch" would be easy to understand as a property name IMO.

**Comment by danielweck** [comment]
Current develop branch code:
https://github.com/readium/readium-desktop/blob/799c80d03775f47f81b50b0799f184ef7e82246f/src/resources/locales/en.json#L112

See:
https://github.com/readium/readium-desktop/commit/799c80d03775f47f81b50b0799f184ef7e82246f#diff-531dfb3b3a69ed357bf08a638e7bf934

https://github.com/readium/readium-desktop/commit/799c80d03775f47f81b50b0799f184ef7e82246f#diff-e2c9e19293210a76adb1046d74cdbfd5R78-R82
