### ISSUE TITLE
Grid view with screen reader, book title read twice

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#568]
The first time it is the label associated with the cover, which is a link to the reading view. 
The second time it is the text below the cover, which is not active.  

Can we hide the second to blind users? or should we make the title + author active and the cover inactive? (it would be the same for keyboard users)

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/586

**Comment by Scarsniik** [comment]
Changing the label of the menu button for "Open the book menu" or something like that would be enough ? Because if we want to have the cover and the menu usable, it needs to be described, no ?

**Comment by danielweck** [comment]
Please take a look at my comment here:
https://github.com/readium/readium-desktop/issues/586#issuecomment-522643666

**Comment by Scarsniik** [comment]
Fixed by #633
