### ISSUE TITLE
app.on("ready") event handling, use app.whenReady() instead

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#580]
Using `app.on("ready")` is fine when the line of code is located at the root of a TypeScript file, such as in `src/main/streamer.ts`:
https://github.com/readium/readium-desktop/blob/7c53921fdca112f2db61190d048a94055e984ff1/src/main/streamer.ts#L48

However, if `app.on("ready")` is invoked from "deeper" code, inside potentially-asynchronous execution paths, then there is a possibility that the `ready` event has already been emitted. For example in `src/main.ts` this is called from a `main()` function, not from the root of the Javascript NodeJS module:

https://github.com/readium/readium-desktop/blob/7c53921fdca112f2db61190d048a94055e984ff1/src/main.ts#L69

Also in `src/main/cli/process.ts`, where `app.on("ready")` is invoked at the same level as the `mainFct()`:
https://github.com/readium/readium-desktop/blob/7c53921fdca112f2db61190d048a94055e984ff1/src/main/cli/process.ts#L98
https://github.com/readium/readium-desktop/blob/7c53921fdca112f2db61190d048a94055e984ff1/src/main/cli/process.ts#L126

So, to be on the safe side, I suggest using the `app.whenReady()` promise instead, which accounts for the already-emitted `ready` event.

**Comment by danielweck** [comment]
Hello Pierre, I've assigned this issue to you because (1) I'd love to hear your thoughts about this, and (2) you implemented the CLI logical layer, so you have a good understanding of the flow of actions when the app is bootstrapped.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/547
(note the `app.whenReady()` usage in the example skeleton / code proposal)

**Comment by panaC** [comment]
I saw this

I think that i solved that

what do you think ?

**Comment by danielweck** [comment]
I think you are referring to this PR:
https://github.com/readium/readium-desktop/pull/606
Yes, this should address this issue (let's see when the PR is finalized).

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/pull/606
