### ISSUE TITLE
OPDS catalog browser: when showing list of publications => extraneous invisible keyboard tabs, and incorrect tab order

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#591]
First keyboard tab:
![ThoriumOPDS1](https://user-images.githubusercontent.com/625201/63060899-66a21100-beeb-11e9-8d42-f30607338585.png)

**Comment by danielweck** [comment]
Next keyboard tab:
![ThoriumOPDS2](https://user-images.githubusercontent.com/625201/63060915-74579680-beeb-11e9-8ad4-5fefed7bb736.png)

**Comment by danielweck** [comment]
Last keyboard tab of the breadcrumb OPDS navigation path:

![ThoriumOPDS3](https://user-images.githubusercontent.com/625201/63060938-8b968400-beeb-11e9-8bc4-5413753885f7.png)

**Comment by danielweck** [comment]
Next keyboard tab (finally goes into the area that it missed before):

![ThoriumOPDS4](https://user-images.githubusercontent.com/625201/63060960-99e4a000-beeb-11e9-8953-2d752cb83df0.png)

**Comment by danielweck** [comment]
Note that this does not occur when the OPDS listing is subcategories, only with a listing of publications.

**Comment by danielweck** [comment]
When testing with a screen reader, the invisible keyoard-tabs seem to be an extraneous / redundant search input text (and associated search button)

**Comment by Scarsniik** [comment]
Fixed in #627
