### ISSUE TITLE
Menu item text way too long, overflows, cannot read the important word

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#592]
![ThoriumMenuLongText](https://user-images.githubusercontent.com/625201/63061024-cbf60200-beeb-11e9-96ae-2f116508d9bb.png)

**Comment by llemeurfr** [comment]
It seems there are two different labels for the same notion: in a different part of the same feed: 

![Capture d'écran 2019-08-16 14 28 01](https://user-images.githubusercontent.com/14943186/63167729-68c2b780-c032-11e9-895d-6fb517071496.png)

**Comment by Scarsniik** [comment]
fixed in #628
