### ISSUE TITLE
OPDS tags should be clickable, to show corresponding categories

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#593]
(this should follow the OPDS hypermedia links defined by the server / inside the OPDS feed itself)

**Comment by danielweck** [comment]
![ThoriumOPDSTagsNoClick](https://user-images.githubusercontent.com/625201/63061110-02338180-beec-11e9-8640-34e9b8d441ea.png)

**Comment by danielweck** [comment]
Relataed issue: https://github.com/readium/readium-desktop/issues/299

**Comment by llemeurfr** [comment]
I disagree. These categories are expressed in the feed as e.g. =
<category label="Fiction" term="FBFIC000000" scheme="http://www.feedbooks.com/categories"/>
<category label="Roman" term="FBFIC019000" scheme="http://www.feedbooks.com/categories"/>
<category label="Littérature britannique" term="INFENGBR" scheme="http://www.feedbooks.com/categories"/>

These are not hyperlinks like search facets (that we'll have to implement later).

**Comment by danielweck** [comment]
Oh I see! (`category`>`label` in OPDS1, `metadata` > `subject` > `name` in OPDS2)

Example publication (OPDS "entry"):

http://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Fcatalog.feedbooks.com%2Fbook%2F1421.atom

...which is linked from:

http://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Fcatalog.feedbooks.com%2Fpublicdomain%2Fbrowse%2Fen%2Ftop.atom

**Comment by danielweck** [comment]
Closing as invalid.

**Comment by danielweck** [comment]
Code reference:
https://github.com/readium/readium-desktop/blob/f2cb0c80b33d321297da3ca7cd664ccf8d8dc69f/src/main/converter/opds.ts#L68-L72
