### ISSUE TITLE
CLI : --help and --version doesn't print

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#611]
./thorium --help or --version doesn't print to screen

**Comment by danielweck** [comment]
Sorry about the `i18next` messages, I corrected it: https://github.com/readium/readium-desktop/issues/610

**Comment by danielweck** [comment]
@panaC is this fixed now?

**Comment by panaC** [comment]
yes fix #649

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/pull/649
