### ISSUE TITLE
ECLINT lint fails in Windows

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#612]
`!src/typings/en.translation.d.ts`
in:
`eclint check '**/*' '!.vscode/**/*' '!.git/**/*' '!node_modules/**/*' '!resources/**/*' '!src/renderer/assets/**/*'
!dist/**/*' '!**/.DS_Store' '!src/typings/en.translation.d.ts'`

**Comment by llemeurfr** [comment]
@danielweck did you manage to correct it?

**Comment by danielweck** [comment]
`npm run lint` does not fail anymore (tested on Windows, MacOS, Linux)
