### ISSUE TITLE
Add full OPDS 2 support

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#613]
Currently the OPDS 2 support is basic. 

A more complete set of possibilities of OPDS 2 should be supported:
- navigation links
- groups
- alternate images (choose the best one).

OPDS 2 spec: https://github.com/opds-community/drafts/blob/master/opds-2.0.md

The main test OPDS 2 feed is https://test.opds.io/2.0/home.json

Other real-life feeds: 
https://catalog.feedbooks.com/catalog/index.json

**Comment by panaC** [comment]
we have to discuss what React components to used, the design layout. before implementing the code logic

**Comment by panaC** [comment]
opds2 feed : https://catalog.feedbooks.com/catalog/index.json

**Comment by panaC** [comment]
Groups implementing here with opds1 : https://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fcirculation.librarysimplified.org%2F
