### ISSUE TITLE
OPDS: when searching from existing "search results page" returns no results, text input remains filled with previous search term

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#623]
![ThoriumOPDSSearch1](https://user-images.githubusercontent.com/625201/63259150-892e8400-c275-11e9-8039-60f99bb17d6d.png)

![ThoriumOPDSSearch2](https://user-images.githubusercontent.com/625201/63259152-8b90de00-c275-11e9-866b-7a15c9ea13a8.png)

**Comment by panaC** [comment]
I cannot reproduce the test case, it works for me. however the search is partially broken in my side

**Comment by danielweck** [comment]
I too am unable to reproduce the bug. This was probably fixed by another PR. Closing issue.
