### ISSUE TITLE
Create a UI related to epub:type=pagebreak

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#645]
From Pierre: 

I think that the page number should be displayed in the bottom slider :

![image](https://user-images.githubusercontent.com/3198865/60446816-76f37a80-9c22-11e9-862d-83eb5d033aab.png)

For now we can access to a specific page without known the page number.
Perhaps we can open an issue with this feature ?

_Originally posted by @panaC in https://github.com/readium/readium-desktop/issues/368#issuecomment-507305711_

**Comment by llemeurfr** [comment]
Related to #20

**Comment by llemeurfr** [comment]
Two markups coexist in the real world:

Markup 1:
```
<span id="page001" title="1" epub:type="pagebreak"/>
```
and Markup 2:
```
<span epub:type="pagebreak" id="page001" class="whatever">1</span>
```

See article: http://sketchytech.blogspot.com/2017/01/when-is-page-break-not-page-break-epub.html

We need samples: are there IDPF samples containing epub:type="pagebreak"?

**Comment by llemeurfr** [comment]
So, instead of trying to display page breaks in the context of the content itself, like Jiminy Panoz tried in #20, could we display page numbers (when present) in the timeline?

**Comment by danielweck** [comment]
> We need samples: are there IDPF samples containing epub:type="pagebreak"?

Sure, wherever there is a `pagelist`, there are `page-breaks` :)
(in the EPUB `epub:type` sense, and/or ARIA `role` mapping equivalents)

All the details are in the original issue:
https://github.com/readium/readium-desktop/issues/82#issuecomment-521457136
(I suggest we don't duplicate info, if we can avoid it)

**Comment by danielweck** [comment]
> Two markups coexist in the real world: ...

Actually, there is also `role` equivalents to `epub:type`, and `aria-label` vs. `title` attributes too. See: https://github.com/readium/readium-desktop/issues/82#issuecomment-526295012

**Comment by danielweck** [comment]
> So, instead of trying to display page breaks in the context of the content itself

I don't think reading systems should do anything special with HTML elements marked with `epub:type="pagebreak"` or `role="doc-pagebreak"` ... content authors can decide (and usually do) to hide skippable items such as "page numbers / breaks" (CSS `display: none` is the usual technique), or to inline versus block-display them, etc.
This is naturally an area where ReadiumCSS could be opinionated, by enforcing design choices (see discussions in https://github.com/readium/readium-desktop/issues/20 ).

So I think we should just focus on what affordances Thorium can offer to expose the "pagelist" nav (not any arbitrary pagebreaks in HTML content documents, but just those that are authored in the EPUB NavDoc).

1) flat, non-hierarchical list (fully visible + scrollable, or on-demand pulldown list) => trivial
2) search input text ("goto page number x") => trivial too (string matching, number radix)
3) maybe some mapping with bottom timeline, but this would require locator computations with percentage progress, just like mapping individual (sub)headings => not trivial

**Comment by JayPanoz** [comment]
Re. ReadiumCSS could be opinionated, it’s worth noting experiments in Readium CSS definitely ended up altering the DOM with pseudo elements – generated content and screen readers already being an issue in and of itself.

**Comment by llemeurfr** [comment]
The reason why I opened this issue separate from #82 is that I thought that page lists (as a nav structure) and page breaks (as inline elements in the HTML content) were two alternative ways to indicate page numbers. I see now that they are complementary (the nav reference points to the inline id).
Before we close this issue and centralize the discussion in #82, a quick question: does EPUBCheck checks in referential integrity of such ref/id system?

**Comment by danielweck** [comment]
> a quick question: does EPUBCheck checks in referential integrity of such ref/id system?

Yes. EPUBCheck verifies the linear order requirement too (within HTML documents, as well as across the spine).

References:

https://github.com/w3c/epubcheck/blob/6af3b9800e1481b634c1fb064afff594207f7357/src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java#L230-L253

https://github.com/w3c/epubcheck/blob/6af3b9800e1481b634c1fb064afff594207f7357/src/test/resources/30/expanded/valid/nav-page-list-reading-order/OPS/nav.xhtml#L15-L22

https://github.com/w3c/epubcheck/blob/6af3b9800e1481b634c1fb064afff594207f7357/src/test/resources/30/expanded/invalid/nav-page-list-unordered-fragments/OPS/nav.xhtml#L14-L20

https://github.com/w3c/epubcheck/blob/6af3b9800e1481b634c1fb064afff594207f7357/src/test/resources/30/expanded/invalid/nav-page-list-unordered-spine/OPS/nav.xhtml#L16-L22

**Comment by danielweck** [comment]
Laurent, can we close this now?
("goto page" feature for EPUB `nav@epub:type="pagelist"` is what we have right now)

**Comment by llemeurfr** [comment]
The "Go to page" feature now added is sufficient. Let's close this issue.
