### ISSUE TITLE
Release v1.0.3 staging

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#664]
The last/latest release tag was/is `v1.0.2`, dated 26 July 2019, created on the `develop` branch:
https://github.com/readium/readium-desktop/releases/tag/v1.0.2

There was no structured changelog between the tag `v1.0.2` and the HEAD of the `master` branch at the time (03 May 2018), because of the huge number of commits between the distant release dates, coupled with the fact that Pull Requests were merged without squashing (thereby making it extremely difficult to extract a CHANGELOG). See:
https://github.com/readium/readium-desktop/commits/26f2fdae1becdc70638a39dd4e96f76dff0786df
=>
https://github.com/readium/readium-desktop/compare/26f2fdae1becdc70638a39dd4e96f76dff0786df...v1.0.2

Note that at this time of writing, the HEAD of the `master` branch is still on 03 May 2018 (we will synchronize `master` with `develop` at the `v1.0.3` milestone):
https://github.com/readium/readium-desktop/commits/master

Now, the commits between the `v1.0.2` tag and the current HEAD of `develop` branch are annotated using the "conventional commits" notation, so we will be able to extract a comprehensible CHANGELOG:
https://github.com/readium/readium-desktop/compare/v1.0.2...develop

Reminder of the recommended method to create the upcoming `v1.0.3` release tag:

```
# Just to double-check the current status - clean, conflict-free local copy of the `develop` branch:

git checkout develop && git pull
git branch && git status && git --no-pager diff
npm run lint && npm run build
```

...note that at this stage, the semantic version in `package.json`, `src/package.json` and `package-lock.json` should be bumped to the appropriate value (i.e. `1.0.3` in this case).

```
# This creates a release tag with a date stamp exactly the same as that of the latest commit (HEAD) at the tip of the `develop` branch:

git tag --list

GIT_COMMITTER_DATE="$(git show develop --format=%aD | head -1)" \
git tag -a "v1.0.3" develop -m "tag v1.0.3" \
&& git push --tags origin develop \
&& git tag --list --format='%(refname)   %(taggerdate)'
```

This can then be followed by a fast-forward merge into the `master` branch (i.e. *no* merge commit):
```
git checkout master && git pull && git log
git merge develop
```

Then, it would probably be a good idea to bump-up semantic versioning in the `develop` branch (by manually updating `package.json`, `src/package.json` and `package-lock.json`), so that further developments and Continuous Integration / Deployment is clearly differentiated from the official latest release, for example `1.0.4-rc.0` (see https://semver.org )

See related issues:
https://github.com/readium/readium-desktop/issues/145
https://github.com/readium/readium-desktop/issues/98

**Comment by llemeurfr** [comment]
I'm ok with this procedure.

**Comment by danielweck** [comment]
- Status Update - 

The head of the `master` branch is at release tag `v1.0.3` attached to commit `71f5e94c1d6eb71f553729e818d2153066633323`:

* https://github.com/readium/readium-desktop/releases/tag/v1.0.3
* https://github.com/readium/readium-desktop/commits/71f5e94c1d6eb71f553729e818d2153066633323

The `master` branch is a copy of the Git commit history of the `develop` branch, created via `git merge` with fast-forward (no merge commit). Consequently, commit `71f5e94c1d6eb71f553729e818d2153066633323` also exists in the `develop` branch, and so does the `v1.0.3` release tag.

The head of the `develop` branch is currently ahead of the `master` branch by one commit, a version bump to `1.0.4-rc.0` for upcoming development in the codebase "trunk":
* https://github.com/readium/readium-desktop/compare/71f5e94c1d6eb71f553729e818d2153066633323...develop

I will generate the `v1.0.3` changelog from the following commit diff:
* https://github.com/readium/readium-desktop/compare/v1.0.2...v1.0.3

**Comment by danielweck** [comment]
Changelog:
https://github.com/readium/readium-desktop/releases/tag/v1.0.3
(please feel free to edit the summary, or to suggest edits here so I can integrate them into the release blurb)
