### ISSUE TITLE
OPDS "add" dialog, hidden "ok" button (only appears when all fields are provided by the user)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#692]
I would suggest showing the "ok" button, in disabled state until fields are completed.
This works better for both sighted users, and blind / screen reader users.

![ThoriumOPDSDialog1](https://user-images.githubusercontent.com/625201/64435968-52e96500-d0bb-11e9-93fa-a8be1e4c7e3b.png)
![ThoriumOPDSDialog2](https://user-images.githubusercontent.com/625201/64435970-52e96500-d0bb-11e9-8978-926ddca3c964.png)

**Comment by llemeurfr** [comment]
fixed via #756
