### ISSUE TITLE
Windows (AppX deployed to Microsoft Store): no "open with" option for EPUB files?

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#697]
I have another Electron app installed "manually" (not via the Store) which has working EPUB file extension associations (i.e. I can choose the app in the "open with" context menu from the file explorer). However, this does not seem to work with Thorium ... is it because the app is not yet public in the Store?

https://github.com/readium/readium-desktop/blob/9799be240bd18a6dde9bc064b8c762e77953d08b/package.json#L113-L124

**Comment by panaC** [comment]
With appx : "open with" doesn't found thorium and worse it appears only the thorium path in list, without action on double click on it.
With msi : "open with" works it appears on the top list, in main windows the publication path is C:\WINDOWS\reader.exe ??

Both doens't works

**Comment by danielweck** [comment]
Current `electron-builder` config for `win` `target` is `msi`:

https://github.com/readium/readium-desktop/blob/1d46e2f6f108b6172e9b1ed146c094c098d84ba9/package.json#L125-L131

... instead, should probably be `nsis`:

https://www.electron.build/configuration/nsis

**Comment by panaC** [comment]
Previous comment : "With msi : "open with" works it appears on the top list, in main windows the publication path is C:\WINDOWS\reader.exe ??" -> fix by replace msi with nsis

as far as appx : 
when i install thorium from microsoft store no key in registry is added for file association..
It's a big deal.

**Comment by danielweck** [comment]
https://github.com/electron-userland/electron-builder/issues/3718

**Comment by panaC** [comment]
https://github.com/electron-userland/electron-builder/issues/3718

**Comment by danielweck** [comment]
We can (maybe) inject a patch via `afterPack`:
https://www.electron.build/configuration/configuration#afterpack
