### ISSUE TITLE
same book imported multiple times into local bookshelf, we need to discriminate the unicity of epub file (hash ?)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#700]
Tested with `npm run cli -- PATH_TO_EPUB`

Related issue: https://github.com/readium/readium-desktop/issues/438

**Comment by panaC** [comment]
We cannot discriminate if the book is imported twice

**Comment by danielweck** [comment]
General discussions: https://github.com/readium/architecture/issues/68

**Comment by danielweck** [comment]
Comment copied across from the other issue:

I don't think we need to hash full EPUB files (even with fast CRC32-like techniques), because publications vary in size enormously (+10MB, +100MB sometimes)

```
import * as crypto from "crypto";

const uniqueStr = ; // for example,
// concatenate the contents of `book.zip!/EPUB/package.opf`
// and the EPUB file size
// (or some other unique-ish metadata,
// but not filename / filesystem location / originating URL, etc.)

const checkSum = crypto.createHash("sha256");
checkSum.update(uniqueStr);
const sha256Hex = checkSum.digest("hex");

// then use `sha256Hex` as a fixed-length unique ID for the EPUB
```

**Comment by danielweck** [comment]
@panaC provided technical pointers:
https://stackoverflow.com/questions/10070293/choosing-a-hash-function-for-best-performance#10074975

https://automationrhapsody.com/md5-sha-1-sha-256-sha-512-speed-performance/

https://github.com/hex7c0/nodejs-hash-performance

https://nodejs.org/api/crypto.html#crypto_determining_if_crypto_support_is_unavailable

**Comment by danielweck** [comment]
The R2-arch discussion (https://github.com/readium/architecture/issues/68) seems to imply that `dc:identifier` should be used for EPUB, so perhaps my proposal to hash `package.opf` + file size isn't necessary? (only for CBZ and other formats that do not have unique ID metadata)

**Comment by llemeurfr** [comment]
In the CLI, I suppose that the EPUB is parsed on import. During parsing, an identifier is generated (either one trusted in the publication metadata or one minted automatically, let's put it on the side for now). The CLI has no user interface. So we could have an --unique option which stops the import if the unicity test fails. If this option is not set, the current behavior stands (duplicates allowed). What do you think of this solution?
