### ISSUE TITLE
Regression: Export does not work anymore

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#724]
Signaled by Microsoft on Windows S. Also experienced on MacOS. 

Steps to Reproduce:

1.      Launch the application.
2.     Select the three dots contextual menu on a book.
3.     Select “Export”.
4.     Notice no action is taken.

Expected result:

The controls within the application should work as expected and should not present “coming soon” messages.

**Comment by panaC** [comment]
It appears was is not an api issues, but more on react html views.
It seems to me, @Scarsniik ?

**Comment by danielweck** [comment]
The "export" feature only fails in this specific case:
1) bookshelf cover view
2) mouse interaction
(works with keyboard interaction, and/or bookshelf list view)
