### ISSUE TITLE
Link.Href is not set! (and no child Links)

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#739]
![image](https://user-images.githubusercontent.com/3198865/65772508-a559f680-e13a-11e9-8557-e4d146e04da1.png)

when i open this ebook : 

[The-Art-of-War.epub.zip](https://github.com/readium/readium-desktop/files/3662926/The-Art-of-War.epub.zip)

This log isn't handle with debug, why ??

**Comment by danielweck** [comment]
Message source:
https://github.com/readium/r2-shared-js/blob/0f31ac6ab96282ecdab4b9dce49729847536c063/src/models/publication-link.ts#L110-L121

**Comment by danielweck** [comment]
I am not able to reproduce, but this message can be ignored. It is an edge case when the `r2-shared-js` parser / (de)serializer announces that it does not find `link` `href` where it expects it (based on the JSON schema of ReadiumWebPubManifest).
