### ISSUE TITLE
When i remove a publication, I cannot import it again

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#740]
test with 
[The-Art-of-War.epub.zip](https://github.com/readium/readium-desktop/files/3662936/The-Art-of-War.epub.zip)

with the + button

**Comment by danielweck** [comment]
No need to remove the EPUB to reproduce the bug: simply attempt to add the same publication using the + button, more than once. Subsequent times fail silently. Yet, this works fine with drag and drop. Strange bug.
