### ISSUE TITLE
in reader topbar button isn't alligned

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#741]
![image](https://user-images.githubusercontent.com/3198865/65774767-37fc9480-e13f-11e9-9758-93f628c2257f.png)

![image](https://user-images.githubusercontent.com/3198865/65774833-56629000-e13f-11e9-9f68-542332b98a60.png)

**Comment by panaC** [comment]
@Scarsniik if you see the source of problem

**Comment by Scarsniik** [comment]
Do you have this problem in the develop branch ? I don't have the same issue

**Comment by panaC** [comment]
you're right strange behaviour, sorry,

**Comment by danielweck** [comment]
I observe the same hairline gap:

![ThoriumToolBarIconsGap](https://user-images.githubusercontent.com/625201/65782228-20280f00-e145-11e9-9715-6ae1588d8022.png)

This minor CSS "rounding error" might be specific to MacOS. Leo, you checked on Linux, right?

**Comment by Scarsniik** [comment]
Yes, I checked on linux
