### ISSUE TITLE
Breadcrumb not sync with browser

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#742]
When i click 3 time on `Derniere mise en ligne` before the url is loaded :

![image](https://user-images.githubusercontent.com/3198865/65775512-9e35e700-e140-11e9-8c17-d0337c958631.png)

![image](https://user-images.githubusercontent.com/3198865/65775490-9413e880-e140-11e9-896e-b3b17df99e55.png)

whereas there is only one `Derniere mise en ligne`

**Comment by panaC** [comment]
@Scarsniik it seems to me that this is more for you, no?

**Comment by Scarsniik** [comment]
How do you click multiple times ? When I click, the page changes instantly

**Comment by panaC** [comment]
you're right, really sorry.
👍 

I went too fast. It's not a problem on develop
