### ISSUE TITLE
error with an opds feed

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#744]
feed :: zone 4 iphone: "http://www.zone4iphone.ru/catalog.php",

when i click on a category : it returns an ebooks link and not a publication list

![image](https://user-images.githubusercontent.com/3198865/65776140-c3772500-e141-11e9-91d0-6e9aadfd64f6.png)

It's this opds feed that is not valid ?

**Comment by danielweck** [comment]
When in doubt, you can use http://readium2.herokuapp.com/opds-v1-v2-convert/ (mirror http://readium2.now.sh/opds-v1-v2-convert/ ) to analyse the OPDS1 XML source (well, the corresponding parsed data model) on the left hand side, and compare with the OPDS2 data model that is generated and used internally (on the right hand side).

That being said, this is not helping in this case (there seems to be a bug somewhere in `r2-streamer-js` with this feed). I am investigating.

**Comment by danielweck** [comment]
I fixed the bug on the streamer side (to visualize the OPDS1/2). But this does not explain the actual bug reported here. There seems to be a bad conversion to `navigation` (should be `publications`)

**Comment by danielweck** [comment]
Okay, I found the problem.
This particular OPDS feed is lacking the `http://opds-spec.org/acquisition` rel in its `application/epub+zip` links. I am implementing a workaround for this edge-case.

**Comment by danielweck** [comment]
So, this issue is now fixed, however the feed still fails to open (linked images and EPUBs) because of relative path URL resolution. Let's file a separate issue for this.
