### ISSUE TITLE
QUID of this ? opds feed with an image in it

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#752]
![image](https://user-images.githubusercontent.com/3198865/65867364-8ba4f300-e376-11e9-9ce6-22b4b206a5ab.png)

**Comment by danielweck** [comment]
OPDS feed link, please?

**Comment by panaC** [comment]
http://opds.openedition.org/

**Comment by danielweck** [comment]
http://opds.openedition.org/?platform=OJ&core=documents&siteName=anatoli

=>

https://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fopds.openedition.org%2F%3Fplatform%3DOJ%26core%3Ddocuments%26siteName%3Danatoli

Alternative link:
https://readium2.now.sh/opds-v1-v2-convert/http%3A%2F%2Fopds.openedition.org%2F%3Fplatform%3DOJ%26core%3Ddocuments%26siteName%3Danatoli

**Comment by danielweck** [comment]
Entry:

```
        {
            "Title": "8, 2017, Les Kurdes : puissance montante au Moyen-Orient ?",
            "Authors": [
                {
                    "Name": "Hamit Bozarslan"
                }
            ],
            "Id": "http://journals.openedition.org/anatoli/590",
            "Summary": "summary",
            "DcIssued": "2017-10-01T00:00:00Z",
            "Updated": "2018-05-12T14:08:44.000Z",
            "Links": [
                {
                    "Type": "image/png",
                    "Href": "http://www.openedition.org/docannexe/image/16107/anatoli_600x281-160x75.png",
                    "Rel": "http://opds-spec.org/image"
                },
                {
                    "Type": "image/png",
                    "Href": "http://www.openedition.org/docannexe/image/16107/anatoli_600x281-160x75.png",
                    "Rel": "http://opds-spec.org/image/thumbnail"
                },
                {
                    "Type": "text/html",
                    "Href": "http://journals.openedition.org/anatoli/590",
                    "Title": "On Revues.org",
                    "Rel": "alternate"
                },
                {
                    "Type": "text/html",
                    "Href": "http://journals.openedition.org/anatoli/590",
                    "Title": "On Revues.org",
                    "Rel": "related"
                }
            ]
        },
```

=> results in OPDS2 `navigation`, but should be link to online HTML page (no OPDS feed / publication directly accessible):
```
                {
                    "Type": "text/html",
                    "Href": "http://journals.openedition.org/anatoli/590",
                    "Title": "On Revues.org",
                    "Rel": "alternate"
                },
```

**Comment by danielweck** [comment]
Instead of "journals", if we pick "books" from the OPDS feed:

http://opds.openedition.org/?platform=OB&core=publishers

=>

https://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fopds.openedition.org%2F%3Fplatform%3DOB%26core%3Dpublishers

alternative link:

https://readium2.now.sh/opds-v1-v2-convert/http%3A%2F%2Fopds.openedition.org%2F%3Fplatform%3DOB%26core%3Dpublishers

...now we see the correct OPDS2 `navigation` followed by `publications`.

**Comment by danielweck** [comment]
So, the "journal" entries (as opposed to "book" entries) are *direct* acquisitions (i.e. not *indirect* acquisitions) to the online HTML landing pages (i.e. no EPUB download link).


Culprit code (needs a patch to handle the "journal" case / online publications):

https://github.com/readium/r2-opds-js/blob/095d1456a06914773cd635e79998cb1d031ce682/src/opds/converter.ts#L245-L302

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/commit/f5d7854125a740ea709e38adc889cb26e8781d1f
(remember to `rm -rf node_modules && npm install && npm run __postinstall`)

See:
https://github.com/readium/r2-opds-js/commit/783f2c50608defa34b7be600bb3280599adb44bd

**Comment by danielweck** [comment]
Note that the `readium-desktop` / Thorium application now needs to handle the edge-case where an OPDS feed does not resolve into an EPUB download link (instead, like an indirect acquisition, there is a `text/html` link to an online journal entry.

**Comment by danielweck** [comment]
Works fine already (no "import" menu option):

![ThoriumOPDSnoEPUB1](https://user-images.githubusercontent.com/625201/65876145-83ea4c00-e380-11e9-8f7b-42959fa8bd64.png)

![ThoriumOPDSnoEPUB2](https://user-images.githubusercontent.com/625201/65876157-89e02d00-e380-11e9-856f-06fd7063fdfe.png)
