### ISSUE TITLE
Request: Provide binary packages (deb/dmg/exe) for latest release

### ISSUE THREAD

**Issue by 86423355844265459587182778** [readium/readium-desktop#769]
I noticed that Thorium Reader (Readium Desktop) version 1.0.4 was released on 06 September 2019, but there are no binary packages (deb/dmg/exe for Linux/macOS/Windows) for 1.0.4 on https://github.com/readium/readium-desktop/releases. The latest binary packages are v1.0.0-alpha.2 which are outdated.

Would you please provide the binary packages so that users can easily install and test this wonderful application? On Linux, I find that Readium Desktop is the only application which displays my Japanese ebooks correctly with East Asian text layout ([vertical text lines running right to left](https://www.w3.org/International/articles/vertical-text/)) and [Furigana](https://en.wikipedia.org/wiki/Furigana). Thank you very much for the great work.

**Comment by llemeurfr** [comment]
We'll provide a DMG and a Linux package very soon now, at the time we release the first public version of Thorium Reader on the Microsoft store (free). We're just making sure that the app is highly accessible (using NVDA / JAWS, Narrator) before we release it. Later, the app will be exposed on the Apple Store also (free).
