### ISSUE TITLE
Filter duplicates in the Library view

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#779]
The library view contains two sections  "Resume reading" and "Recently added". 
There is no good reason to have ebooks present in both sections. 
We'll therefore filter ebooks from the "Recently added" section if they are present in the "Resume reading" section.

**Comment by danielweck** [comment]
Good idea. Also, I really dislike the fact that when I import a publication (OPDS feed or drag+drop), the EPUB / cover image is (visually) added to the library section that I cannot see (bottom part).
Of course I understand that "resume reading" should be immediately accessible, but perhaps we could programmatically "scroll to" the part of the UI that has been updated?
