### ISSUE TITLE
OPDS "buy" acquisition link only used in popup menu, missing in publication info panel

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#781]
See screenshots:
![ThoriumOPDSBuy1](https://user-images.githubusercontent.com/625201/66582039-0c36d100-eb79-11e9-8fa1-aa078dd2ec81.png)
![ThoriumOPDSBuy2](https://user-images.githubusercontent.com/625201/66582042-0e009480-eb79-11e9-88e0-a9f7cee0a58b.png)

**Comment by danielweck** [comment]
Feedbooks OPDS "best sellers":
https://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Fcatalog.feedbooks.com%2Fstore%2Fbrowse%2Fen%2Ftop.atom

Dedicated publication OPDS info:
https://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Fcatalog.feedbooks.com%2Fitem%2F2459861.atom

**Comment by danielweck** [comment]
Here is the NYPL demo browser:
http://opds-browser-demo.herokuapp.com/collection/https%3A%2F%2Fcatalog.feedbooks.com%2Fstore%2Fbrowse%2Fen%2Ftop.atom/
 (https://catalog.feedbooks.com/store/browse/en/top.atom)

**Comment by Scarsniik** [comment]
I fixed the problem in #804 for the buy link but for the other links I don't really know where to put it because if I put it on the same place, there will be a lot of link

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/commit/17e79eebfaa6fbc3872e5c1c7aec1f7abbe804b8
