### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by ways2read** [readium/readium-desktop#791]
In the English version we have a couple of French words creeping in:
Settings / Display / **Disposition** 
Settings / Display/ **Alignement**

**Comment by panaC** [comment]
i fixed only Alignment. Disposition is an english word, right ?

**Comment by ways2read** [comment]
You are correct, ‘disposition’ is an English word, but not really understood in this instance. It is usually used to refer to someone's manner, like ‘ a sunny disposition’.

Kindle has a toggle for ‘continuous scrolling’. I think ‘scrolling mode’ or ‘layout’ would be well understood.

Richard

**Comment by panaC** [comment]
@danielweck which words you prefer ?

**Comment by danielweck** [comment]
layout +1
