### ISSUE TITLE
Unlabeled buttons in Navigation / Bookmarks

### ISSUE THREAD

**Issue by ways2read** [readium/readium-desktop#796]
When a bookmark has been created it is possible to edit the name and delete the bookmark. The buttons to do this are unlabeled and so are spoken simply as "button" by a screen reader.

![image](https://user-images.githubusercontent.com/9092859/66765894-bc237b80-eea4-11e9-817a-f2474ee3a4e4.png)

**Comment by danielweck** [comment]
Indeed, thank you for reporting this!

Leo, I assigned you, but feel free to unassign if you are not able to take on this development task.

https://github.com/readium/readium-desktop/blob/1788e321d9e91b98ca6b094292d500bfe555f3ac/src/renderer/components/reader/ReaderMenu.tsx#L287-L292

**Comment by danielweck** [comment]
Suggested fix: add `title={ __("reader.bookmarks.edit|delete")}` attributes to the SVG elements.
