### ISSUE TITLE
Why the Next button is enabled when there is only one page ?

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#820]
Why button Next enabled whereas only one page ?

![image](https://user-images.githubusercontent.com/3198865/67396302-99c9e600-f5a7-11e9-86ef-9b5f491636fd.png)

feedbooks / new & noteworthly

**Comment by danielweck** [comment]
This was reported back here:
https://github.com/readium/readium-desktop/pull/733#issuecomment-536010972

...it is a bug in the Feedbooks OPDS feed.

**Comment by panaC** [comment]
related to #822

**Comment by danielweck** [comment]
@panaC is this fixed now?

**Comment by panaC** [comment]
Yes I have removed the page number. But the feedbooks feed always brings up the next page link on empty page.
