### ISSUE TITLE
When importing an opds publication fails, the 'import' button is no longer active in the feed.

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#826]
I see this behaviour on all opds feed with low access time

example with http://srv.manybooks.net/opds/

http://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fmanybooks.net%2Fopds%2Ftitle_detail.php%3Ftid%3Dleightother16theunveiling

**Comment by danielweck** [comment]
This should be fixed by https://github.com/readium/readium-desktop/pull/843/
