### ISSUE TITLE
OPDS FEED: check the file extension of acquisition link

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#831]
When the file is the type .pdf , the downloader throw an error without explanation.

May be add the type file in publication info, with a specific alert message when the user want to download it.

**Comment by danielweck** [comment]
Note that this PR https://github.com/readium/readium-desktop/pull/843
introduces a check for EPUB content type:
https://github.com/readium/readium-desktop/pull/843/files#diff-798e25491a613033ecb4f411ffadb06eR178

...however, we are still only parsing the *first* acquisition link (open-access, or sample/preview), therefore we are probably missing out on multiple content types.
