### ISSUE TITLE
Cover image translation (alt attribute)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#833]
https://github.com/readium/readium-desktop/blob/9f1e226c4fc93420b039becbc68e236be0d4f5bd/src/renderer/components/publication/Cover.tsx#L64

**Comment by panaC** [comment]
ah sorry, i didn't think it was useful

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-desktop/blob/f1251186bd99cd7f9c6bca5fe9f3563f548a9d31/src/renderer/common/components/Cover.tsx#L86
