### ISSUE TITLE
apiAction promise 5s timeout on long operations (e.g. "publication/import" download + LCP LSD updates)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#837]
Thankfully, the `apiAction` promise "resolved" state is not used in these cases (and the "rejected" promise state via `catch` is only used to display an error message in the console, no adverse effect in UI state):

https://github.com/readium/readium-desktop/blob/a893796613b88a23a0520127f41d5b09f8d62c30/src/renderer/components/catalog/PublicationAddButton.tsx#L54-L56

https://github.com/readium/readium-desktop/blob/a893796613b88a23a0520127f41d5b09f8d62c30/src/renderer/components/dialog/FileImport.tsx#L69-L71

**Comment by danielweck** [comment]
Culprit:
https://github.com/readium/readium-desktop/blob/a893796613b88a23a0520127f41d5b09f8d62c30/src/renderer/apiAction.ts#L63-L66

**Comment by panaC** [comment]
already fixed with #836 - WIP
