### ISSUE TITLE
Opt-in EPUB file extension association ("double-click from filesystem to open publication")

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#85]
CBZ too?

This should work on all 3 target distribution platforms Windows, Linux and MacOS

**Comment by danielweck** [comment]
Related: https://github.com/edrlab/readium-desktop/issues/25

**Comment by danielweck** [comment]
Electron doc:
https://github.com/electron-userland/electron-builder/blob/master/docs/generated/PlatformSpecificBuildOptions.md
(look for `fileAssociations`)

Electron code:
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/src/options/FileAssociation.ts

**Comment by llemeurfr** [comment]
I'm supporting the idea of "taking" the CBZ extension.

**Comment by danielweck** [comment]
Also consider custom URL protocol/scheme handler:
https://electronjs.org/docs/api/app#appsetasdefaultprotocolclientprotocol-path-args
(both Windows and MacOS)

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/readium-desktop/issues/150

**Comment by panaC** [comment]
cf ln 234 in main.ts

```
app.on("open-url", (event: any, url: any) => {
    event.preventDefault();
    // Process url: import or open?
});
app.on("open-file", (event: any, url: any) => {
    event.preventDefault();
    // Process file: import or open?
});
```

**Comment by danielweck** [comment]
https://github.com/readium/readium-desktop/blob/541e48bbe45407a8918018e0076d4ca5ebecd68b/src/main.ts#L254-L261
