### ISSUE TITLE
When changing language, tab headers only refresh when switching tab (regression)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#882]
I think this is a regression from this PR:
https://github.com/readium/readium-desktop/pull/879/files#diff-a1228900df8ff573cefb675232bfceb2
(not 100% sure, but the `__` translate props looks suspicious)

**Comment by panaC** [comment]
very strange, i will investigate it, thanks

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-desktop/issues/897
