### ISSUE TITLE
JS error, uncaught exception (on Windows)

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#889]
This happened on a Windows machine. The app was in background (maybe after being closed) and there were issues with the internet connection on this machine.  
![Bug thorium](https://user-images.githubusercontent.com/14943186/71086200-88f9b300-2199-11ea-8859-beea5c27c1ce.PNG)

**Comment by danielweck** [comment]
Culprit (`response` is null/undefined when `err` is truthy):
https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/common/utils/http.ts#L82-L101
