### ISSUE TITLE
wrong navigation header language when the app is launched

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#897]
Move the app in French. Close it. 
Reopen it. The navigation header + the second level (search / All books) are in English, the other parts are in French. 
Select Catalogs -> the navigation header is now in French. 

It seems to be a bad initialization of the navigation header.

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-desktop/issues/882

**Comment by panaC** [comment]
it's crasy, only from the middle of the window that this is translated

![image](https://user-images.githubusercontent.com/3198865/71476729-d522a400-27e6-11ea-980a-4c7e4da7fe69.png)

**Comment by panaC** [comment]
the 18n locale is set with redux and redux-saga during the rendering react componnent.
With the actual load on redux state manager, this updating take a while time. And I think the translator is updated during the catalog rendering and not before (default english) .. I will investigate how solve this timing translator propagation.
