### ISSUE TITLE
new copy of state in each redux reducer loop

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#911]
src/renderer/redux/reducers/reader.ts - ln 46
src/main/redux/reducers/reader.ts - ln 46

**Comment by danielweck** [comment]
https://github.com/readium/readium-desktop/blob/8b570a31683208868ae8aeb5af81db960be3dd10/src/renderer/redux/reducers/reader.ts#L46

https://github.com/readium/readium-desktop/blob/8b570a31683208868ae8aeb5af81db960be3dd10/src/main/redux/reducers/reader.ts#L46

**Comment by danielweck** [comment]
Isn't that the same as (for example):
https://github.com/readium/readium-desktop/blob/8b570a31683208868ae8aeb5af81db960be3dd10/src/renderer/redux/reducers/api.ts#L100-L102

**Comment by danielweck** [comment]
Oh, I see:
https://github.com/readium/readium-desktop/blob/8b570a31683208868ae8aeb5af81db960be3dd10/src/renderer/redux/reducers/reader.ts#L61-L62

...yes, I agree that the "new state" instance should only be created in individual `switch` cases.

**Comment by panaC** [comment]
fixed with #930
