### ISSUE TITLE
Images are not displayed properly

### ISSUE THREAD

**Issue by 86423355844265459587182778** [readium/readium-desktop#917]
##### SUMMARY
Thorium Reader v1.1.1 does not display images properly (when the image does not fit the window), cropping part of the image.

##### STEPS TO REPRODUCE
1. Open a [light novel](https://en.wikipedia.org/wiki/Light_novel) EPUB file.
2. Adjusting the settings does not help.

##### OBSERVED RESULT
![1](https://user-images.githubusercontent.com/47747986/72213122-3209a400-34e1-11ea-9c78-7ef491addbf3.png)

##### EXPECTED RESULT
([Readium Chrome app](https://chrome.google.com/webstore/detail/readium/fepbnnnkkadjhjahcafoaglimekefifl) is being used in the below screenshot.)
![2](https://user-images.githubusercontent.com/47747986/72213143-83b22e80-34e1-11ea-8646-754ab0122059.png)

##### OTHER INFORMATION
OS: Linux
EPUB used in the above examples: 痛いのは嫌なので防御力に極振りしたいと思います。８ ([Wikipedia article](https://en.wikipedia.org/wiki/BOFURI:_I_Don%27t_Want_to_Get_Hurt,_so_I%27ll_Max_Out_My_Defense.))

**Comment by danielweck** [comment]
Thank you for the bug report!
Are you able to share the EPUB (privately, with Thorium devs), so we can test/debug at our end?

**Comment by 86423355844265459587182778** [comment]
@danielweck 
Okay.
Is [this Keybase account yours](https://keybase.io/danielweck)? Can I send you the file through Keybase?

**Comment by danielweck** [comment]
Yes, that's [me on KeyBase](https://keybase.io/danielweck). Thank you!

**Comment by danielweck** [comment]
Using `r2-testapp-js` (which is based on the same rendering/layout engine as Thorium / `readium-desktop`), the initial image / chapter looks weird:

![Screenshot 2020-01-14 at 11 30 52](https://user-images.githubusercontent.com/625201/72341178-866b7a00-36c1-11ea-9646-42bfae87a59a.png)

**Comment by danielweck** [comment]
Actually, all images look "corrupted", and it varies from time to time, for example I also get the following:

![Screenshot 2020-01-14 at 11 33 47](https://user-images.githubusercontent.com/625201/72341281-c03c8080-36c1-11ea-8c35-703e83c35def.png)

**Comment by danielweck** [comment]
Note that RTL (Right To Left) + VWM (Vertical Writing Mode) text rendering "works", but page/CSS-column navigation is broken, see:
https://github.com/readium/r2-navigator-js/issues/42

**Comment by 86423355844265459587182778** [comment]
For the time being, I recommend using the old version [v1.0.0-alpha.2](https://github.com/readium/readium-desktop/releases) in case someone is affected by #917 and/or readium/r2-navigator-js#42. The old version does not have these two bugs.

**Comment by danielweck** [comment]
The issue of corrupted images was fixed via https://github.com/readium/readium-desktop/commit/f1251186bd99cd7f9c6bca5fe9f3563f548a9d31

**Comment by danielweck** [comment]
Image resizing is a broader issue that is discussed in ReadiumCSS (`object-fit: contain` and other authoring practices to prevent image breaking across page boundaries)

**Comment by 86423355844265459587182778** [comment]
Thanks!

Where can I track the image resizing discussion? readium/readium-css/55 seems to be related but it has been closed.

**Comment by danielweck** [comment]
> (BTW Is 1.2.0 released? I see [the tag here](https://github.com/readium/readium-desktop/releases) but it has no summary or installation files.)

Official release (version `1.2.1`):

https://github.com/readium/readium-desktop/releases/tag/v1.2.0

Latest builds:

https://github.com/readium/readium-desktop/releases

**Comment by danielweck** [comment]
> Where can I track the image resizing discussion? readium/readium-css/55 seems to be related but it has been closed.

I wonder if this is related to https://github.com/readium/readium-css/issues/50 ?
