### ISSUE TITLE
Electron Windows won't open until generated data is cleared

### ISSUE THREAD

**Issue by brettins** [readium/readium-desktop#936]
Windows 10 Pro
Version 1903
OS Build 18362.592

When I run `npm start:dev` and there is already data populated in `C:\Users\[user]\AppData\Roaming\EDRLab.ThoriumReader` no windows will appear. 

This makes it very difficult to debug instances of reloading the app - in my case I am writing an analytics database and need sync data about the app closing and opening, and syncing closing app data when I need to delete the database to re-run the app prevents this. 

Electron processes are present in Task Manager, and terminal output seems normal.

https://gist.github.com/brettins/6bf70e0169b660d36ed402221a5129d8

Deleting the `Roaming\EDRLab.ThoriumReader` and running `npm start:dev` will cause the windows to open, but must be deleted every time before compile.

**Comment by panaC** [comment]
if you checkout on `develop` and delete `AppData\Roaming\EDRLab.ThoriumReader`.
At each `npm run start:dev` you have to remove AppData folder ?

On macOS, i didn't have this problem

**Comment by brettins** [comment]
That's correct.

**Comment by danielweck** [comment]
It this still a reproducible bug, @brettins ?
I am not able to reproduce this problem, I am afraid.

**Comment by brettins** [comment]
Sorry, I thought I responded to this. After updating I no longer experience the problem.
