### ISSUE TITLE
readium-desktop  Does not support smil, but browser plugins support smil

### ISSUE THREAD

**Issue by huaimutou** [readium/readium-desktop#939]
Will the desktop version support smil?

**Comment by danielweck** [comment]
Yes, Thorium / the `readium-desktop` SDK will support EPUB3 Media Overlays in the near future.

**Comment by llemeurfr** [comment]
the support of EPUB media overlays (i.e. smil) being in the roadmap, I propose to close this issue. The release of this feature will be communicated broadly.

**Comment by vkiranmaniya** [comment]
Hello, @danielweck is there any update of smil?

**Comment by danielweck** [comment]
the feature is being implemented, the central part works fine, nearly all the edge cases are covered. watch this space.
