### ISSUE TITLE
audiobooks: ReadiumCSS settings in reader view, most unnecessary (only preserve night mode?)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#944]
Follow-up to PR https://github.com/readium/readium-desktop/pull/938

**Comment by panaC** [comment]
What is the purpose of this issue ?

**Comment by llemeurfr** [comment]
When listening to an audiobook, Display, Spacing, MathML settings are not useful.   

Re. Them settings, i.e. night mode, it is useful only is it works for the whole page display (it does not currently).  Can we inject Theme CSS info params into the audiobook view?  
Re. Text settings (font type and size) one could argue that it is useful for title display.

**Comment by danielweck** [comment]
night and sepia themes *do* work in the audiobook navigator renderer. otherwise, it is a new bug which must be filed. laurent, what code révision / build are you using? (how/when did you see this bug?)

**Comment by danielweck** [comment]
readiumCSS *is* injected and applied to audiobooks navigator.

**Comment by llemeurfr** [comment]
I installed the night build some days ago (don't remember the exact date). I'll update it now and report.

**Comment by llemeurfr** [comment]
No problem anymore after the update.

**Comment by llemeurfr** [comment]
Re. Text settings, what do you think Daniel? do we keep it active for a11y reasons? I assume we should.

**Comment by danielweck** [comment]
yes, i would preserve font size, font family, color theme (dark/night, sepia), and i would remove pagination/layout, mathjax, and line/word spacing.
