### ISSUE TITLE
l10n: Spanish "about app" information file is missing

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#972]
@nvdaes would you mind taking a look at the following file, and could you please let us know if you are able to translate the text to Spanish? Many thanks!

https://github.com/readium/readium-desktop/blob/develop/src/resources/information/en.md

PS, this issue is a follow-up to the successfully-merged PR https://github.com/readium/readium-desktop/pull/957

**Comment by nvdaes** [comment]
@danielweck , sorry for the delay, just seeing this. I will take care ASAP, hopely in a few days. Thanks for including spanish translation!

**Comment by nvdaes** [comment]
This is fixed in #1006

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-desktop/pull/1006
