### ISSUE TITLE
Images are only partially displayed in some situations

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#986]
On Thorium 1.2, the images of a certain Adobe Pages sample are cut; it wasn't the case with Thorium 1.1. The version of Electron (7 -> 8) may be the source of the issue. 

[Here is a link to this sample](https://drive.google.com/open?id=15Iga1Lsk9-FyQju70RxF53yvXZOTZvrO).

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/commit/f1251186bd99cd7f9c6bca5fe9f3563f548a9d31
