### ISSUE TITLE
capital T on Thorium 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#991]
On the Mac version at least, the app name in the top navigation bar is "thorium". Same for the app name in the tray.

 A capital T on Thorium would be cool.

**Comment by panaC** [comment]
https://github.com/readium/readium-desktop/blob/f1251186bd99cd7f9c6bca5fe9f3563f548a9d31/package.json#L75

https://github.com/readium/readium-desktop/blob/738d908d51cc103d0b845a33fb75a247227f6fd9/webpack.config-preprocessor-directives.js#L39

https://github.com/readium/readium-desktop/blob/8b83bb22171cf8dc26597b0df25ee8515998b9bf/src/preprocessor-directives.ts#L41-L42

https://github.com/readium/readium-desktop/search?q=_APP_NAME&unscoped_q=_APP_NAME

**Comment by danielweck** [comment]
Thank you Pierre ;)

`const capitalizedAppName = _APP_NAME.charAt(0).toUpperCase() + _APP_NAME.substring(1);`

**Comment by danielweck** [comment]
`productName`:

https://www.electron.build/configuration/configuration#configuration

**Comment by danielweck** [comment]
I don't think we can override `productName` for the Mac DMG: https://www.electron.build/configuration/dmg

...so maybe the only solution is to change `productName` to `Thorium`, but we need to check for regressions with the Linux and Windows builds, and the CLI executable.

**Comment by panaC** [comment]
![image](https://user-images.githubusercontent.com/3198865/78367872-0ae3df80-75c3-11ea-8ac0-40b422749e87.png)

little problem :
https://github.com/readium/readium-desktop/blob/f1251186bd99cd7f9c6bca5fe9f3563f548a9d31/package.json#L2

I don't think you can replace the project name without changing the product ID of the appx needed to update on the Microsoft store.
I tried a while ago.
