### ISSUE TITLE
non-rectangular cover images in the bookshelf, different aspect ratios (particularly: square-ish audio cover images)

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#993]
Because audiobook covers are square (usually at least), there is a large space between the 'Resume listening' label and the first line of covers. 

We'd like to make this space smaller. But will we always have square covers for audiobooks? nobody knows. Any idea on how to solve it?

**Comment by danielweck** [comment]
I noticed this too. Handling variable aspect ratios is not easy. There are off-the-shelf layout algorithms / components that do it right, but I don't think the techniques would translate to our horizontal scroll layout.

**Comment by panaC** [comment]
we can convert the audiobooks covers to any desired square format before being displayed on the screen and thus define a fixed vertical dimension for the audiobooks

**Comment by llemeurfr** [comment]
Not necessarily a bad idea but then covers which would not be square would be cropped in an ugly way.

**Comment by danielweck** [comment]
I propose this:

## BEFORE:

![ThoriumCoverImages_BEFORE](https://user-images.githubusercontent.com/625201/79204401-6b311780-7e34-11ea-99eb-2ff24d44a980.png)

## AFTER:

![ThoriumCoverImages_AFTER](https://user-images.githubusercontent.com/625201/79204424-7126f880-7e34-11ea-9d9e-ae11c55b7bde.png)

**Comment by danielweck** [comment]
PR: https://github.com/readium/readium-desktop/pull/1002

**Comment by llemeurfr** [comment]
Effectively centering vertically would give a better look, in front of such a diversity of cover formats. 
It was the case before, but without this grey line container; the cover was therefore lost in the white space. It is better this way.

**Comment by llemeurfr** [comment]
Also, Resume Listening should be moved up IMO, appearing only if there are audiobooks in the bookshelf.
